Repository OpenCTI-Platform/connectors, pull requests merged in 2024-06, with the labels that each got.

#2197 [Malbeacon] Fix import environment variable in converter
  internal-enrichment/malbeacon/src/main.py
  internal-enrichment/malbeacon/src/malbeacon_converter.py
Labels: filigran team

#2198 [Urlscan] Fix import environment variable from docker
  internal-enrichment/urlscan-enrichment/src/main.py
  internal-enrichment/urlscan-enrichment/src/urlscan_enrichment_services/converter_to_stix2.py
Labels: filigran team

#2200 [import-document] Fix alias mapping for Country
  internal-import-file/import-document/src/reportimporter/config/entity_config.ini
Labels: filigran team

#2190 [import-document] make import-document compatible with Analysis connector type
  internal-import-file/import-document/src/config.yml.sample
  internal-import-file/import-document/src/reportimporter/core.py
  internal-import-file/import-document/src/reportimporter/report_parser.py
Labels: filigran team, multi-repository

#2217 [import-document] added push_analysis in analysis request handling (opencti/6803)
  internal-import-file/import-document/src/reportimporter/constants.py
  internal-import-file/import-document/src/reportimporter/core.py
Labels: filigran team

#2154 [Crowdstrike Feed] Rework the Crowdstrike feed connector to use FalconPy library
  external-import/crowdstrike/src/config.yml.sample
  external-import/crowdstrike/src/crowdstrike_feeds_connector/__init__.py
  external-import/crowdstrike/src/crowdstrike_feeds_connector/actor/__init__.py
  external-import/crowdstrike/src/crowdstrike_feeds_connector/actor/builder.py
  external-import/crowdstrike/src/crowdstrike_feeds_connector/actor/importer.py
  external-import/crowdstrike/src/crowdstrike_feeds_connector/core.py
  external-import/crowdstrike/src/crowdstrike_feeds_connector/importer.py
  external-import/crowdstrike/src/crowdstrike_feeds_connector/indicator/__init__.py
  external-import/crowdstrike/src/crowdstrike_feeds_connector/indicator/builder.py
  external-import/crowdstrike/src/crowdstrike_feeds_connector/indicator/importer.py
  external-import/crowdstrike/src/crowdstrike_feeds_connector/py.typed
  external-import/crowdstrike/src/crowdstrike_feeds_connector/report/__init__.py
  external-import/crowdstrike/src/crowdstrike_feeds_connector/report/builder.py
  external-import/crowdstrike/src/crowdstrike_feeds_connector/report/importer.py
  external-import/crowdstrike/src/crowdstrike_feeds_connector/rule/__init__.py
  external-import/crowdstrike/src/crowdstrike_feeds_connector/rule/snort_suricata_master_builder.py
  external-import/crowdstrike/src/crowdstrike_feeds_connector/rule/snort_suricata_master_importer.py
  external-import/crowdstrike/src/crowdstrike_feeds_connector/rule/yara_master_builder.py
  external-import/crowdstrike/src/crowdstrike_feeds_connector/rule/yara_master_importer.py
  external-import/crowdstrike/src/crowdstrike_feeds_services/__init__.py
  external-import/crowdstrike/src/crowdstrike_feeds_services/client/__init__.py
  external-import/crowdstrike/src/crowdstrike_feeds_services/client/actors.py
  external-import/crowdstrike/src/crowdstrike_feeds_services/client/base_api.py
  external-import/crowdstrike/src/crowdstrike_feeds_services/client/indicators.py
  external-import/crowdstrike/src/crowdstrike_feeds_services/client/reports.py
  external-import/crowdstrike/src/crowdstrike_feeds_services/client/rules.py
  external-import/crowdstrike/src/crowdstrike_feeds_services/utils/__init__.py
  external-import/crowdstrike/src/crowdstrike_feeds_services/utils/config_variables.py
  external-import/crowdstrike/src/crowdstrike_feeds_services/utils/constants.py
  external-import/crowdstrike/src/crowdstrike_feeds_services/utils/indicators.py
  external-import/crowdstrike/src/crowdstrike_feeds_services/utils/observables.py
  external-import/crowdstrike/src/crowdstrike_feeds_services/utils/report_fetcher.py
  external-import/crowdstrike/src/crowdstrike_feeds_services/utils/snort_parser.py
  external-import/crowdstrike/src/crowdstrike_feeds_services/utils/yara_parser.py
  external-import/crowdstrike/src/main.py
  external-import/crowdstrike/src/requirements.txt
Labels: filigran team

#2246 add new env MISP_DATE_FILTER_FIELD
  external-import/misp/README.md
  external-import/misp/docker-compose.yml
  external-import/misp/src/config.yml.sample
  external-import/misp/src/misp.py
Labels: community

#2149 [Taxii2] Option to pull data from custom property and put in a label
  external-import/taxii2/README.md
  external-import/taxii2/src/config.yml.sample
  external-import/taxii2/src/taxii2.py
Labels: community
