Repository OpenCTI-Platform/connectors, pull requests merged in 2024-08, with the labels that each got.

#2416 [Sekoia] Adding related threat
  external-import/sekoia/src/config.yml.sample
  external-import/sekoia/src/sekoia.py
Labels: filigran team

#2455 Update README Fortinet
  external-import/fortinet-ti/README.md
Labels: filigran team

#2450 [HarfangLab] Fix bug create observable
  stream/harfanglab/src/harfanglab.py
Labels: bug, filigran team

#2468 [Mandiant] Create 2 new environment variables for creating CPE or not for software and limit number of relationships
  external-import/mandiant/README.md
  external-import/mandiant/src/connector/base.py
  external-import/mandiant/src/connector/reports.py
Labels: filigran team

#2474 Updated Ransomware
  external-import/ransomwarelive/docker-compose.yml
  external-import/ransomwarelive/src/lib/ransomConn.py
Labels: community

#2465 [Malpedia] Adding variable default_marking, and schedule_unit
  external-import/malpedia/README.md
  external-import/malpedia/src/config.yml.sample
  external-import/malpedia/src/main.py
  external-import/malpedia/src/malpedia_connector/malpedia.py
  external-import/malpedia/src/malpedia_services/config_variables.py
  external-import/malpedia/src/malpedia_services/converter_to_stix.py
Labels: filigran team

#2482 [Sentinel] Update Documentation
  stream/sentinel/README.md
  stream/sentinel/doc/permission_mandatory.png
  stream/sentinel/doc/sentinel_info_variables.png
Labels: filigran team

#2493 [Mandiant] Handle multiple standard ID for a software when importing a report + fix state when entity use epoch time
  external-import/mandiant/src/connector/base.py
  external-import/mandiant/src/connector/reports.py
Labels: filigran team

#2499 [Malpedia] Fix default_marking recovery error and update readme
  external-import/malpedia/README.md
  external-import/malpedia/src/malpedia_connector/malpedia.py
Labels: bug, filigran team

#2503 [VirusTotal Livehunt Notification] Fix issue on json dump
  external-import/virustotal-livehunt-notifications/src/livehunt/builder.py
Labels: filigran team

#2497 [Sekoia] Fix extension and fix related_objects
  external-import/sekoia/src/sekoia.py
Labels: bug, filigran team

#2516 [Safebrowsing] Add connector to Circle CI
  .circleci/config.yml
Labels: filigran team

#2518 [CrowdStrike] Fix KeyError for missing 'description' in report
  external-import/crowdstrike/src/crowdstrike_feeds_connector/report/importer.py
  external-import/crowdstrike/src/crowdstrike_feeds_services/utils/__init__.py
  external-import/crowdstrike/src/crowdstrike_feeds_services/utils/report_fetcher.py
Labels: bug, filigran team

#2521 [connector] Float values are not exported on csv (#7951)
  internal-export-file/export-file-csv/src/export-file-csv.py
Labels: filigran team

#2536 [Mandiant] Send bundle for each report and its context
  external-import/mandiant/src/connector/base.py
Labels: filigran team

#2524 [Cofense] NEW Cofense connector from Cofense
  .circleci/config.yml
  external-import/cofense/.gitignore
  external-import/cofense/Dockerfile
  external-import/cofense/README.md
  external-import/cofense/docker-compose.yml
  external-import/cofense/entrypoint.sh
  external-import/cofense/src/__init__.py
  external-import/cofense/src/config.yml.sample
  external-import/cofense/src/main.py
  external-import/cofense/src/requirements.txt
Labels: filigran team

#2553 [Cofense] Fix entrypoint
  external-import/cofense/docker-compose.yml
  external-import/cofense/entrypoint.sh
  external-import/cofense/src/config.yml.sample
  external-import/cofense/src/main.py
Labels: filigran team

#2581 [Mandiant] Fix fail to parse if end_epoch is None
  external-import/mandiant/src/connector/base.py
Labels: bug, filigran team
