Repository OpenCTI-Platform/connectors, pull requests merged in 2024-07, with the labels that each got.

#2211 [HarfangLab] Improvement logger and readme
  stream/harfanglab/README.md
  stream/harfanglab/src/harfanglab.py
Labels: filigran team

#2273 [RedFlag] Add type of connector in config sample file
  external-import/red-flag-domains/src/config.yml.sample
Labels: filigran team

#2239 [CHRONICLE] Fix + doc
  stream/chronicle/readme.md
  stream/chronicle/src/chronicle.py
  stream/chronicle/src/requirements.txt
Labels: community

#2286 [Chronicle] Fix lint chronicle connector
  stream/chronicle/src/chronicle.py
Labels: filigran team

#2292 [Recorded Future] Fix import TA as individual when type of Person from RF
  external-import/recorded-future/src/rflib/rf_to_stix2.py
Labels: filigran team

#2297 [Mandiant] Add campaign first_seen date
  external-import/mandiant/src/connector/campaigns.py
Labels: filigran team

#2305 [Mandiant] Correctly import Mandiant report news analysis
  external-import/mandiant/src/connector/__main__.py
  external-import/mandiant/src/connector/reports.py
Labels: filigran team

#2310 Adding the Infoblox connector
  external-import/infoblox/Dockerfile
  external-import/infoblox/README.md
  external-import/infoblox/docker-compose.yml
  external-import/infoblox/entrypoint.sh
  external-import/infoblox/src/config.yml.sample
  external-import/infoblox/src/infoblox.py
  external-import/infoblox/src/requirements.txt
  external-import/threatfox/src/main.py
Labels: filigran team

#2322 [Crowdstrike] Fix Infinit loop
  external-import/crowdstrike/src/crowdstrike_feeds_connector/report/importer.py
Labels: bug, filigran team

#2332 [connector] Fix mandiant relationships
  external-import/mandiant/src/connector/reports.py
Labels: filigran team

#2308 Add possibility to exclude IOCs import based on labels
  external-import/crowdstrike/README.md
  external-import/crowdstrike/docker-compose.yml
  external-import/crowdstrike/src/config.yml.sample
  external-import/crowdstrike/src/crowdstrike_feeds_connector/core.py
  external-import/crowdstrike/src/crowdstrike_feeds_connector/indicator/builder.py
  external-import/crowdstrike/src/crowdstrike_feeds_connector/indicator/importer.py
  external-import/crowdstrike/src/crowdstrike_feeds_services/utils/config_variables.py
Labels: filigran team

#2340 Fix KeyError on dict
  external-import/infoblox/src/infoblox.py
Labels: filigran team

#2344 [Flashpoint] Fix lint Flashpoint
  external-import/flashpoint/src/mispfeed.py
Labels: filigran team

#2350 [Recorded Future Enrichment] Add score in the correct field
  internal-enrichment/recordedfuture-enrichment/src/rflib/rf_to_stix2.py
Labels: filigran team

#2356 [cape-sandbox] - fix docker-compose.yml template
  internal-enrichment/cape-sandbox/docker-compose.yml
  internal-enrichment/cape-sandbox/src/cape-sandbox.py
  internal-enrichment/cape-sandbox/src/config.yml.sample
Labels: filigran team

#2371 [Mandiant] Add log when exception is caught outside of running connector process
  external-import/mandiant/src/connector/__main__.py
Labels: filigran team

#2193 [Webhook] Init connector
  .circleci/config.yml
  stream/webhook/Dockerfile
  stream/webhook/README.md
  stream/webhook/docker-compose.yml
  stream/webhook/entrypoint.sh
  stream/webhook/src/requirements.txt
  stream/webhook/src/webhook.py
Labels: community

#2381 [Splunk] Add traceback to have more accurate logs
  stream/splunk/src/splunk.py
Labels: filigran team

#2384 [Ironnet] Fix error on running connector
  external-import/ironnet/src/ironnet/__main__.py
Labels: filigran team

#2385 [Webhook] Fix circle ci configuration file for more consistency
  .circleci/config.yml
Labels: filigran team

#2386 [Webhook] Update version to fix CI build
  stream/webhook/Dockerfile
  stream/webhook/docker-compose.yml
  stream/webhook/src/requirements.txt
Labels: filigran team

#2347 [Sentinel] - Indicator updates are not propagated in Azure Sentinel
  stream/sentinel/README.md
  stream/sentinel/docker-compose.yml
  stream/sentinel/src/config.yml.sample
  stream/sentinel/src/sentinel.py
  stream/sentinel/src/sightings.py
Labels: filigran team

#2388 [Misp] Fix indent + add traceback for logs outside connector main process
  external-import/misp/src/misp.py
Labels: filigran team

#2415 [Malpedia] Fix missing description for intrusion set
  external-import/malpedia/src/malpedia_connector/malpedia.py
Labels: bug

#2417 [Google DNS] Make the connector 'playbook compatible'
  internal-enrichment/google-dns/src/main.py
Labels: filigran team

#2422 [Mandiant] Improvement of campaign imports
  external-import/mandiant/src/connector/campaigns.py
  external-import/mandiant/src/connector/common.py
Labels: filigran team

#2436 [Mandiant] Fix argument method extract mandiant name
  external-import/mandiant/src/connector/campaigns.py
Labels: filigran team
