Repository OpenCTI-Platform/connectors, pull requests merged in 2024-12, with the labels that each got.

#3040 [ExportReportPdf] list params fixed (#9082)
  internal-export-file/export-report-pdf/src/export-report-pdf.py
Labels: filigran team

#2793 Create a connector for the Loader Insight Agency File Feed
  external-import/loaderinsightagency/Dockerfile
  external-import/loaderinsightagency/README.md
  external-import/loaderinsightagency/docker-compose.yml
  external-import/loaderinsightagency/entrypoint.sh
  external-import/loaderinsightagency/src/config.yml.sample
  external-import/loaderinsightagency/src/main.py
  external-import/loaderinsightagency/src/requirements.txt
Labels: community

#3022 [CrowdStrike] Add new filter: CROWDSTRIKE_REPORT_TARGET_INDUSTRIES
  external-import/crowdstrike/README.md
  external-import/crowdstrike/docker-compose.yml
  external-import/crowdstrike/src/config.yml.sample
  external-import/crowdstrike/src/crowdstrike_feeds_connector/core.py
  external-import/crowdstrike/src/crowdstrike_feeds_connector/report/importer.py
  external-import/crowdstrike/src/crowdstrike_feeds_services/utils/config_variables.py
Labels: filigran team

#2994 [ExportReportPdf] Convert entity's description from markdown to HTML
  internal-export-file/export-report-pdf/src/export-report-pdf.py
  internal-export-file/export-report-pdf/src/requirements.txt
  internal-export-file/export-report-pdf/src/resources/case.html
  internal-export-file/export-report-pdf/src/resources/report.css.template
  internal-export-file/export-report-pdf/src/resources/report.html
Labels: filigran team

#3046 [Mandiant] Fix status complete on the progress bar for reports
  external-import/mandiant/src/connector/base.py
  external-import/mandiant/src/connector/constants.py
Labels: bug, filigran team

#3053 [crtsh] fix import issues
  external-import/crtsh/src/crtsh/core/crtsh.py
  external-import/crtsh/src/crtsh/core/crtsh_utils.py
  external-import/crtsh/src/lib/external_import.py
  external-import/crtsh/src/main.py
Labels: filigran team

#3073 [All] - unit tests appear as ok even though non zero exit status code
  .gitignore
  external-import/harfanglab-incidents/src/test-requirements.txt
  internal-enrichment/first-epss/src/first_epss_connector_tests/__init__.py
  internal-enrichment/first-epss/src/first_epss_connector_tests/common_fixtures.py
  internal-enrichment/first-epss/src/first_epss_connector_tests/fixtures/data_sample.json
  internal-enrichment/first-epss/src/first_epss_connector_tests/test_first_epss_connector.py
  internal-enrichment/first-epss/src/test-requirements.txt
  internal-enrichment/riskiq-passive-total/tests/__init__.py
  internal-enrichment/riskiq-passive-total/tests/common_fixtures.py
  internal-enrichment/riskiq-passive-total/tests/fixtures/data_sample.json
  internal-enrichment/riskiq-passive-total/tests/test-requirements.txt
  internal-enrichment/riskiq-passive-total/tests/test_riskiq_passive_total_connector.py
  internal-enrichment/urlscan-enrichment/src/test-requirements.txt
  run_test.sh
  stream/crowdstrike-endpoint-security/src/requirements.txt
Labels: bug, filigran team

#3070 [LIAFileFeed] add connector to circleci
  .circleci/config.yml
  external-import/lia-file-feed/Dockerfile
  external-import/lia-file-feed/README.md
  external-import/lia-file-feed/docker-compose.yml
  external-import/lia-file-feed/entrypoint.sh
  external-import/lia-file-feed/src/config.yml.sample
  external-import/lia-file-feed/src/main.py
  external-import/lia-file-feed/src/requirements.txt
  external-import/loaderinsightagency/README.md
Labels: filigran team

#2971 [Feedly connector] use source name as author
  external-import/feedly/src/feedly/opencti_connector/connector.py
  external-import/feedly/src/feedly/opencti_connector/runner.py
Labels: community

#3065 [Tagger] Add a capacity to the Tagger connector
  internal-enrichment/tagger/README.md
  internal-enrichment/tagger/src/connector.py
Labels: filigran team

#3016 Update importDocument docker-compose.yml
  internal-import-file/import-document/docker-compose.yml
Labels: filigran team

#3063 Update default MISP docker-compose.yml to avoid confusion
  external-import/misp/docker-compose.yml
  external-import/misp/src/config.yml.sample
Labels: filigran team

#3079 [Recorded Future] handle exception raised when no attachment and no object_refs to report
  external-import/recorded-future/src/rflib/rf_client.py
  external-import/recorded-future/src/rflib/rf_to_stix2.py
Labels: filigran team

#3030 [TEMPLATE] create init script
  templates/create_connector_dir.sh
Labels: community

#3051 [Connector] Fix bug in WorldWatch report entities crawling
  external-import/orange-cyberdefense/src/orange-cyberdefense.py
Labels: bug, partner

#3081 [Tenable Vuln Management] - Integrate source api changes
  external-import/tenable-vuln-management/src/tenable_vuln_management/connector.py
  external-import/tenable-vuln-management/src/tenable_vuln_management/models/common.py
  external-import/tenable-vuln-management/src/tenable_vuln_management/models/tenable.py
  external-import/tenable-vuln-management/tests/test_converter_to_stix.py
  external-import/tenable-vuln-management/tests/test_models/resources/tenable_api_response.json
  external-import/tenable-vuln-management/tests/test_models/test_tenable.py
Labels: filigran team

#3124 [Harfanglab-Intel] Add publish docker image
  .circleci/config.yml
Labels: bug, filigran team

#3069 [The Hive] - Change confusing logger level
  external-import/thehive/src/hive_observable_transform.py
  external-import/thehive/src/thehive.py
Labels: filigran team

#3126 [Harfanglab-Incidents] Add publish docker image
  .circleci/config.yml
Labels: bug, filigran team

#3128 [CircleCI] Add a build_4 and build_rolling_4 (Bug #3127)
  .circleci/config.yml
Labels: bug, filigran team

#2988 [Zerofox] Add format changes to malware endpoint and country entities
  external-import/zerofox/src/collectors/mappers/malwareToMalware.py
  external-import/zerofox/src/collectors/mappers/ransomwareToMalware.py
  external-import/zerofox/src/open_cti/domain_objects.py
  external-import/zerofox/src/requirements.txt
Labels: partner

#3138 [Intel471_v2] Adding intel471v_v2 in CircleCI
  .circleci/config.yml
Labels: filigran team

#3044 [Tenable Security Center]: Connector Initial Creation
  .circleci/config.yml
  external-import/tenable-security-center/Dockerfile
  external-import/tenable-security-center/README.md
  external-import/tenable-security-center/app.py
  external-import/tenable-security-center/config.yaml.sample
  external-import/tenable-security-center/docker-compose.yml.sample
  external-import/tenable-security-center/env.sample
  external-import/tenable-security-center/pyproject.toml
  external-import/tenable-security-center/tenable_security_center/__init__.py
  external-import/tenable-security-center/tenable_security_center/adapters/__init__.py
  external-import/tenable-security-center/tenable_security_center/adapters/config/__init__.py
  external-import/tenable-security-center/tenable_security_center/adapters/config/config_yaml.py
  external-import/tenable-security-center/tenable_security_center/adapters/config/env.py
  external-import/tenable-security-center/tenable_security_center/adapters/tsc_api/__init__.py
  external-import/tenable-security-center/tenable_security_center/adapters/tsc_api/v5_13_common.py
  external-import/tenable-security-center/tenable_security_center/adapters/tsc_api/v5_13_from_asset.py
  external-import/tenable-security-center/tenable_security_center/domain/__init__.py
  external-import/tenable-security-center/tenable_security_center/domain/entities.py
  external-import/tenable-security-center/tenable_security_center/domain/use_case.py
  external-import/tenable-security-center/tenable_security_center/ports/__init__.py
  external-import/tenable-security-center/tenable_security_center/ports/asset.py
  external-import/tenable-security-center/tenable_security_center/ports/config.py
  external-import/tenable-security-center/tenable_security_center/ports/errors.py
  external-import/tenable-security-center/tenable_security_center/py.typed
  external-import/tenable-security-center/tenable_security_center/utils.py
  external-import/tenable-security-center/tests/conftest.py
  external-import/tenable-security-center/tests/test-requirements.txt
  external-import/tenable-security-center/tests/tests_domain/test_entities.py
  external-import/tenable-security-center/tests/tests_domain/test_use_cases.py
Labels: filigran team, do not merge

#3121 [Zvelo] Create a connector to download Zvelo intel
  .circleci/config.yml
  external-import/zvelo/.dockerignore
  external-import/zvelo/Dockerfile
  external-import/zvelo/README.md
  external-import/zvelo/docker-compose.yml
  external-import/zvelo/entrypoint.sh
  external-import/zvelo/src/config.yml.sample
  external-import/zvelo/src/main.py
  external-import/zvelo/src/requirements.txt
  external-import/zvelo/src/zvelo_connector/__init__.py
  external-import/zvelo/src/zvelo_connector/client_api.py
  external-import/zvelo/src/zvelo_connector/config_variables.py
  external-import/zvelo/src/zvelo_connector/connector.py
  external-import/zvelo/src/zvelo_connector/converter_to_stix.py
  external-import/zvelo/src/zvelo_connector/utils.py
Labels: filigran team

#3149 [Harfanglab incidents] feat: configuration loader raises explicit error if missing required variables
  external-import/harfanglab-incidents/README.md
  external-import/harfanglab-incidents/src/harfanglab_incidents_connector/config_variables.py
Labels: bug, filigran team

#3100 [Google SecOps SIEM] Create Google SecOps SIEM connector
  .circleci/config.yml
  stream/google-secops-siem/.dockerignore
  stream/google-secops-siem/Dockerfile
  stream/google-secops-siem/README.md
  stream/google-secops-siem/__docs__/media/dashboard.png
  stream/google-secops-siem/__docs__/media/rate-limit.png
  stream/google-secops-siem/__docs__/media/stream-configuration.png
  stream/google-secops-siem/dashboard/opencti-dashboard.yaml
  stream/google-secops-siem/docker-compose.yml
  stream/google-secops-siem/entrypoint.sh
  stream/google-secops-siem/src/config.yml.sample
  stream/google-secops-siem/src/main.py
  stream/google-secops-siem/src/requirements.txt
  stream/google-secops-siem/src/secops_siem_connector/__init__.py
  stream/google-secops-siem/src/secops_siem_connector/connector.py
  stream/google-secops-siem/src/secops_siem_services/__init__.py
  stream/google-secops-siem/src/secops_siem_services/api_client.py
  stream/google-secops-siem/src/secops_siem_services/config_loader.py
  stream/google-secops-siem/src/secops_siem_services/cti_converter.py
  stream/google-secops-siem/src/secops_siem_services/utils.py
  stream/google-secops-siem/tests/__init__.py
  stream/google-secops-siem/tests/common_fixtures.py
  stream/google-secops-siem/tests/fixtures/octi_indicator_no_id_sample.json
  stream/google-secops-siem/tests/fixtures/octi_indicator_sample.json
  stream/google-secops-siem/tests/fixtures/octi_observable_values_sample.json
  stream/google-secops-siem/tests/fixtures/udm_metadata_sample.json
  stream/google-secops-siem/tests/test-requirements.txt
  stream/google-secops-siem/tests/test_converter_to_udm.py
Labels: filigran team

#3166 [Google-secops-siem] Fix path in CircleCI the working directory
  .circleci/config.yml
Labels: bug, filigran team

#3181 [Sentinel Incidents] Fix documentation images
  external-import/sentinel-incidents/README.md
  external-import/sentinel-incidents/doc/permission_mandatory.png
  external-import/sentinel-incidents/doc/sentinel_info_variables.png
Labels: filigran team

#3186 [Recorded Future] Handle properly incident ID generation and created and updated dates + correct markdown format
  external-import/recorded-future/src/rflib/make_markdown_table.py
  external-import/recorded-future/src/rflib/rf_playbook_alerts.py
Labels: filigran team

#3183 VirusTotal Livehunt Notifications plyara - no attribute logger
  external-import/virustotal-livehunt-notifications/src/livehunt/builder.py
Labels: filigran team

#3024 Update HarfangLab config.yml.sample
  stream/harfanglab-intel/src/config.yml.sample
Labels: filigran team

#3187 [HARFANGLAB INCIDENTS] - Unsafe Alert Process attributes access when creating File
  external-import/harfanglab-incidents/src/harfanglab_incidents_connector/client_api.py
  external-import/harfanglab-incidents/src/harfanglab_incidents_connector/connector.py
  external-import/harfanglab-incidents/src/harfanglab_incidents_connector/converter_to_stix.py
  external-import/harfanglab-incidents/src/harfanglab_incidents_connector/models/opencti.py
Labels: bug, filigran team
