Repository OpenCTI-Platform/connectors, pull requests merged in 2024-09, with the labels that each got.

#2459 [Sekoia/Crowdstrike/Mandiant/AlienVault/RecordedFuture/CisaKEV] Modification on connector to use the new pycti connector helper scheduler
  external-import/alienvault/README.md
  external-import/alienvault/docker-compose.yml
  external-import/alienvault/src/alienvault/core.py
  external-import/alienvault/src/alienvault/importer.py
  external-import/alienvault/src/config.yml.sample
  external-import/cisa-known-exploited-vulnerabilities/README.md
  external-import/cisa-known-exploited-vulnerabilities/docker-compose.yml
  external-import/cisa-known-exploited-vulnerabilities/src/config.yml.sample
  external-import/cisa-known-exploited-vulnerabilities/src/main.py
  external-import/crowdstrike/README.md
  external-import/crowdstrike/docker-compose.yml
  external-import/crowdstrike/src/config.yml.sample
  external-import/crowdstrike/src/crowdstrike_feeds_connector/actor/importer.py
  external-import/crowdstrike/src/crowdstrike_feeds_connector/core.py
  external-import/crowdstrike/src/crowdstrike_feeds_connector/importer.py
  external-import/crowdstrike/src/crowdstrike_feeds_connector/indicator/importer.py
  external-import/crowdstrike/src/crowdstrike_feeds_connector/report/importer.py
  external-import/crowdstrike/src/crowdstrike_feeds_connector/rule/snort_suricata_master_importer.py
  external-import/crowdstrike/src/crowdstrike_feeds_connector/rule/yara_master_importer.py
  external-import/crowdstrike/src/crowdstrike_feeds_services/utils/config_variables.py
  external-import/mandiant/README.md
  external-import/mandiant/docker-compose.yml
  external-import/mandiant/src/config.yml.sample
  external-import/mandiant/src/connector/__main__.py
  external-import/mandiant/src/connector/actors.py
  external-import/mandiant/src/connector/base.py
  external-import/mandiant/src/connector/campaigns.py
  external-import/mandiant/src/connector/indicators.py
  external-import/mandiant/src/connector/reports.py
  external-import/mandiant/src/connector/vulnerabilities.py
  external-import/recorded-future/README.md
  external-import/recorded-future/docker-compose.yml
  external-import/recorded-future/src/config.yml.sample
  external-import/recorded-future/src/main.py
  external-import/recorded-future/src/rflib/risk_list.py
  external-import/recorded-future/src/rflib/threat_map.py
  external-import/sekoia/README.md
  external-import/sekoia/src/config.yml.sample
  external-import/sekoia/src/sekoia.py
Labels: filigran team, do not merge

#2635 [Shodan] Add to readme
  internal-enrichment/shodan/README.md
  internal-enrichment/shodan/__docs__/media/trigger-filters.png
Labels: filigran team

#2653 [Crowdstrike] Fix error bytes-like object is required, and fix error logger
  external-import/crowdstrike/src/crowdstrike_feeds_connector/rule/yara_master_importer.py
  external-import/crowdstrike/src/crowdstrike_feeds_services/utils/report_fetcher.py
Labels: bug, filigran team

#2636 [Shodan] Save results to note
  internal-enrichment/shodan/docker-compose.yml
  internal-enrichment/shodan/src/config.yml.sample
  internal-enrichment/shodan/src/shodanImport.py
Labels: community

#2676 [Crowdstrike] Fix "'FetchedReport' not subscriptable" errors
  external-import/crowdstrike/src/crowdstrike_feeds_connector/indicator/builder.py
Labels: filigran team

#2703 [Tanium] fix : wrong argument name when calling pycti method
  stream/tanium/src/sightings.py
  stream/tanium/src/tanium.py
  stream/tanium/src/tanium_api_handler.py
  stream/tanium/tests/test-requirements.txt
  stream/tanium/tests/test_tanium_import_modules.py
Labels: bug, filigran team

#2554 [Alienvault, CrowdStrike, Phishunt, ThreatFox, URLHaus] added the ability to set x_opencti_score for select connectors
  external-import/alienvault/README.md
  external-import/alienvault/docker-compose.yml
  external-import/alienvault/src/alienvault/builder.py
  external-import/alienvault/src/alienvault/core.py
  external-import/alienvault/src/alienvault/importer.py
  external-import/alienvault/src/alienvault/utils/__init__.py
  external-import/alienvault/src/alienvault/utils/constants.py
  external-import/alienvault/src/alienvault/utils/observables.py
  external-import/alienvault/src/config.yml.sample
  external-import/crowdstrike/README.md
  external-import/crowdstrike/docker-compose.yml
  external-import/crowdstrike/src/config.yml.sample
  external-import/crowdstrike/src/crowdstrike_feeds_connector/core.py
  external-import/crowdstrike/src/crowdstrike_feeds_connector/indicator/builder.py
  external-import/crowdstrike/src/crowdstrike_feeds_connector/indicator/importer.py
  external-import/crowdstrike/src/crowdstrike_feeds_services/utils/__init__.py
  external-import/crowdstrike/src/crowdstrike_feeds_services/utils/config_variables.py
  external-import/phishunt/docker-compose.yml
  external-import/phishunt/src/config.yml.sample
  external-import/phishunt/src/phishunt.py
  external-import/threatfox/README.md
  external-import/threatfox/docker-compose.yml
  external-import/threatfox/src/config.yml.sample
  external-import/threatfox/src/main.py
  external-import/urlhaus/docker-compose.yml
  external-import/urlhaus/src/config.yml.sample
  external-import/urlhaus/src/urlhaus.py
Labels: community, do not merge
