Repository OpenCTI-Platform/connectors, pull requests merged in 2024-10, with the labels that each got.

#2740 [greynoise-vuln] Add new GreyNoise Vulnerability internal enrichment connector (v2)
  internal-enrichment/greynoise-vuln/.dockerignore
  internal-enrichment/greynoise-vuln/.gitignore
  internal-enrichment/greynoise-vuln/Dockerfile
  internal-enrichment/greynoise-vuln/README.md
  internal-enrichment/greynoise-vuln/docker-compose.yml
  internal-enrichment/greynoise-vuln/entrypoint.sh
  internal-enrichment/greynoise-vuln/src/config.yml.sample
  internal-enrichment/greynoise-vuln/src/main.py
  internal-enrichment/greynoise-vuln/src/requirements.txt
Labels: partner support

#2739 fixed threatfox doc
  external-import/threatfox/README.md
Labels: community

#2742 [Crowdstrike] Improve connector and indicators ingestion
  external-import/crowdstrike/src/crowdstrike_feeds_connector/actor/importer.py
  external-import/crowdstrike/src/crowdstrike_feeds_connector/core.py
  external-import/crowdstrike/src/crowdstrike_feeds_connector/importer.py
  external-import/crowdstrike/src/crowdstrike_feeds_connector/indicator/importer.py
  external-import/crowdstrike/src/crowdstrike_feeds_connector/report/importer.py
  external-import/crowdstrike/src/crowdstrike_feeds_connector/rule/snort_suricata_master_importer.py
  external-import/crowdstrike/src/crowdstrike_feeds_connector/rule/yara_master_importer.py
Labels: filigran team

#2743 [Greynoise Vuln] Add greynoise-vuln enrichment connector in CI/CD
  .circleci/config.yml
  internal-enrichment/greynoise-vuln/docker-compose.yml
Labels: filigran team

#2737 [CISA KEV]: Do not republish all the content at each execution
  external-import/cisa-known-exploited-vulnerabilities/src/main.py
Labels: filigran team

#2761 [importExternalReference] Bypasses certain security measures when generating a PDF or MD
  internal-enrichment/import-external-reference/src/import-external-reference.py
Labels: bug, filigran team

#2766 [VirusTotal] Fix TypeError: can only concatenate str (not NoneType) to str
  internal-enrichment/virustotal/README.md
  internal-enrichment/virustotal/src/virustotal/virustotal.py
Labels: bug, filigran team

#2782 [Sentinel connectors] add config to .circleci
  .circleci/config.yml
Labels: filigran team

#2805 [RiskIQ] set Main Observable type for indicators
  external-import/riskiq/src/riskiq/article_importer.py
Labels: community support

#2759 [Tenable-Vuln-Management]: Connector initial creation
  .circleci/config.yml
  external-import/tenable-vuln-management/.dockerignore
  external-import/tenable-vuln-management/Dockerfile
  external-import/tenable-vuln-management/README.md
  external-import/tenable-vuln-management/docker-compose.yml
  external-import/tenable-vuln-management/entrypoint.sh
  external-import/tenable-vuln-management/requirements.txt
  external-import/tenable-vuln-management/src/__init__.py
  external-import/tenable-vuln-management/src/config.yml.sample
  external-import/tenable-vuln-management/src/main.py
  external-import/tenable-vuln-management/src/tenable_vuln_management/__init__.py
  external-import/tenable-vuln-management/src/tenable_vuln_management/client_api.py
  external-import/tenable-vuln-management/src/tenable_vuln_management/config_variables.py
  external-import/tenable-vuln-management/src/tenable_vuln_management/connector.py
  external-import/tenable-vuln-management/src/tenable_vuln_management/converter_to_stix.py
  external-import/tenable-vuln-management/src/tenable_vuln_management/models/__init__.py
  external-import/tenable-vuln-management/src/tenable_vuln_management/models/common.py
  external-import/tenable-vuln-management/src/tenable_vuln_management/models/opencti.py
  external-import/tenable-vuln-management/src/tenable_vuln_management/models/tenable.py
  external-import/tenable-vuln-management/test-requirements.txt
  external-import/tenable-vuln-management/tests/test_converter_to_stix.py
  external-import/tenable-vuln-management/tests/test_models/resources/tenable_api_response.json
  external-import/tenable-vuln-management/tests/test_models/test_opencti.py
  external-import/tenable-vuln-management/tests/test_models/test_tenable.py
Labels: feature, filigran team

#2797 [Crowdstrike] Fix API Base URL variable name incorrectly defined
  external-import/crowdstrike/src/crowdstrike_feeds_services/utils/config_variables.py
Labels: filigran team

#2821 Issue/1450 tenable vuln management
  external-import/tenable-vuln-management/README.md
  external-import/tenable-vuln-management/src/tenable_vuln_management/converter_to_stix.py
  external-import/tenable-vuln-management/src/tenable_vuln_management/models/opencti.py
  external-import/tenable-vuln-management/tests/test_converter_to_stix.py
Labels: feature, filigran team

#2698 [Tanium] Create two connectors (external import and stream) to replace actual Tanium Stream connector
  .circleci/config.yml
  external-import/tanium-incidents/.dockerignore
  external-import/tanium-incidents/.gitignore
  external-import/tanium-incidents/Dockerfile
  external-import/tanium-incidents/README.md
  external-import/tanium-incidents/doc/source.png
  external-import/tanium-incidents/doc/workflow.png
  external-import/tanium-incidents/docker-compose.yml
  external-import/tanium-incidents/entrypoint.sh
  external-import/tanium-incidents/src/config.yml.sample
  external-import/tanium-incidents/src/main.py
  external-import/tanium-incidents/src/requirements.txt
  external-import/tanium-incidents/src/tanium_incidents_connector/__init__.py
  external-import/tanium-incidents/src/tanium_incidents_connector/client_api.py
  external-import/tanium-incidents/src/tanium_incidents_connector/config_variables.py
  external-import/tanium-incidents/src/tanium_incidents_connector/connector.py
  external-import/tanium-incidents/src/tanium_incidents_connector/converter_to_stix.py
  external-import/tanium-incidents/src/tanium_incidents_connector/utils.py
  stream/tanium-intel/.dockerignore
  stream/tanium-intel/.gitignore
  stream/tanium-intel/Dockerfile
  stream/tanium-intel/README.md
  stream/tanium-intel/doc/source.png
  stream/tanium-intel/doc/workflow.png
  stream/tanium-intel/docker-compose.yml
  stream/tanium-intel/entrypoint.sh
  stream/tanium-intel/src/config.yml.sample
  stream/tanium-intel/src/main.py
  stream/tanium-intel/src/requirements.txt
  stream/tanium-intel/src/tanium_intel_connector/__init__.py
  stream/tanium-intel/src/tanium_intel_connector/api_handler.py
  stream/tanium-intel/src/tanium_intel_connector/config_variables.py
  stream/tanium-intel/src/tanium_intel_connector/connector.py
  stream/tanium-intel/src/tanium_intel_connector/intel_cache.py
  stream/tanium-intel/src/tanium_intel_connector/intel_manager.py
  stream/tanium-intel/src/tanium_intel_connector/utils.py
  stream/tanium/README.md
  stream/tanium/src/import_manager.py
  stream/tanium/src/sightings.py
  stream/tanium/src/tanium_api_handler.py
Labels: filigran team

#2851 [Connectors] Downgrade Python version to 3.11 as stix-shifter is not compatible
  stream/harfanglab/Dockerfile
  stream/qradar/Dockerfile
  stream/sentinel-intel/Dockerfile
  stream/sentinel/Dockerfile
  stream/splunk/Dockerfile
  stream/webhook/Dockerfile
Labels: dependencies, filigran team, security

#2852 [import-external-reference] Downgrade Python version to 3.11 connector use a lib which is not compatible with Python 3.12 in Dockerfile
  internal-enrichment/import-external-reference/Dockerfile
Labels: dependencies, filigran team, security

#2854 [import-external-reference] Add lib to use with playwright
  internal-enrichment/import-external-reference/Dockerfile
Labels: dependencies, filigran team, security

#2856 [import-external-reference] Change distribution to bookworm as playrwright cannot be used with alpine
  internal-enrichment/import-external-reference/Dockerfile
Labels: dependencies, filigran team, security

#2858 [Yara] Remove from yara unecessary lib
  internal-enrichment/yara/Dockerfile
Labels: dependencies, filigran team, security

#2859 [yara] Remove apt-get from yara Dockerfile
  internal-enrichment/yara/Dockerfile
Labels: dependencies, filigran team, security

#2855 [Tanium] add try/except clause to log error on connector's launch
  stream/tanium/src/tanium.py
Labels: bug, filigran team
