Repository OpenCTI-Platform/connectors, pull requests merged in 2024-05, with the labels that each got.

#1983 [Crowdstrike Endpoint Security] Rework stream connector and allow update event
  internal-enrichment/google-dns/src/__init__.py
  internal-enrichment/google-dns/src/tests/__init__.py
  internal-enrichment/google-dns/src/tests/test_client.py
  run_test.sh
  stream/crowdstrike-endpoint-security/README.md
  stream/crowdstrike-endpoint-security/__docs__/media/ces-demo.gif
  stream/crowdstrike-endpoint-security/__docs__/media/create-stream.png
  stream/crowdstrike-endpoint-security/__docs__/media/event-ces.gif
  stream/crowdstrike-endpoint-security/__docs__/media/logs-platform.png
  stream/crowdstrike-endpoint-security/__docs__/media/stream-no-file.png
  stream/crowdstrike-endpoint-security/docker-compose.yml
  stream/crowdstrike-endpoint-security/entrypoint.sh
  stream/crowdstrike-endpoint-security/src/__tests__/__init__.py
  stream/crowdstrike-endpoint-security/src/__tests__/common_fixtures.py
  stream/crowdstrike-endpoint-security/src/__tests__/fixtures/data_stream_sample.json
  stream/crowdstrike-endpoint-security/src/__tests__/fixtures/event_create_indicator_sample.json
  stream/crowdstrike-endpoint-security/src/__tests__/fixtures/event_delete_indicator_sample.json
  stream/crowdstrike-endpoint-security/src/__tests__/fixtures/event_update_indicator_sample.json
  stream/crowdstrike-endpoint-security/src/__tests__/fixtures/response_file_hash_sample.json
  stream/crowdstrike-endpoint-security/src/__tests__/test_crowdstrike.py
  stream/crowdstrike-endpoint-security/src/config.yml.sample
  stream/crowdstrike-endpoint-security/src/connector/__init__.py
  stream/crowdstrike-endpoint-security/src/connector/crowdstrike.py
  stream/crowdstrike-endpoint-security/src/crowdstrike.py
  stream/crowdstrike-endpoint-security/src/main.py
  stream/crowdstrike-endpoint-security/src/requirements.txt
  stream/crowdstrike-endpoint-security/src/services/__init__.py
  stream/crowdstrike-endpoint-security/src/services/client.py
  stream/crowdstrike-endpoint-security/src/services/config_variables.py
  stream/crowdstrike-endpoint-security/src/services/constants.py
  stream/crowdstrike-endpoint-security/src/services/metrics.py
  stream/crowdstrike-endpoint-security/src/test-requirements.txt
Labels: filigran team

#2075 [Malpedia] Refactor the connector to use stix bundle
  external-import/malpedia/README.md
  external-import/malpedia/docker-compose.yml
  external-import/malpedia/entrypoint.sh
  external-import/malpedia/src/__tests__/__init__.py
  external-import/malpedia/src/__tests__/test_malpedia.py
  external-import/malpedia/src/connector/__init__.py
  external-import/malpedia/src/connector/malpedia.py
  external-import/malpedia/src/main.py
  external-import/malpedia/src/malpedia.py
  external-import/malpedia/src/malpedia/__init__.py
  external-import/malpedia/src/malpedia/client.py
  external-import/malpedia/src/malpedia/core.py
  external-import/malpedia/src/malpedia/knowledge.py
  external-import/malpedia/src/malpedia/models.py
  external-import/malpedia/src/malpedia/utils.py
  external-import/malpedia/src/requirements.txt
  external-import/malpedia/src/services/__init__.py
  external-import/malpedia/src/services/client.py
  external-import/malpedia/src/services/config_variables.py
  external-import/malpedia/src/services/constants.py
  external-import/malpedia/src/services/converter_to_stix.py
  external-import/malpedia/src/services/models.py
  external-import/malpedia/src/services/utils.py
  external-import/malpedia/src/test-requirements.txt
Labels: filigran team

#2095 [All connectors] Fix naming folders for tests
  external-import/malpedia/src/malpedia_connector/__init__.py
  external-import/malpedia/src/malpedia_connector/malpedia.py
  external-import/malpedia/src/malpedia_services/__init__.py
  external-import/malpedia/src/malpedia_services/client.py
  external-import/malpedia/src/malpedia_services/config_variables.py
  external-import/malpedia/src/malpedia_services/constants.py
  external-import/malpedia/src/malpedia_services/converter_to_stix.py
  external-import/malpedia/src/malpedia_services/models.py
  external-import/malpedia/src/malpedia_services/utils.py
  external-import/malpedia/src/malpedia_tests/__init__.py
  external-import/malpedia/src/malpedia_tests/test_malpedia.py
  stream/crowdstrike-endpoint-security/src/__tests__/__init__.py
  stream/crowdstrike-endpoint-security/src/crowdstrike_connector/__init__.py
  stream/crowdstrike-endpoint-security/src/crowdstrike_connector/crowdstrike.py
  stream/crowdstrike-endpoint-security/src/crowdstrike_services/__init__.py
  stream/crowdstrike-endpoint-security/src/crowdstrike_services/client.py
  stream/crowdstrike-endpoint-security/src/crowdstrike_services/config_variables.py
  stream/crowdstrike-endpoint-security/src/crowdstrike_services/constants.py
  stream/crowdstrike-endpoint-security/src/crowdstrike_services/metrics.py
  stream/crowdstrike-endpoint-security/src/crowdstrike_tests/__init__.py
  stream/crowdstrike-endpoint-security/src/crowdstrike_tests/common_fixtures.py
  stream/crowdstrike-endpoint-security/src/crowdstrike_tests/fixtures/data_stream_sample.json
  stream/crowdstrike-endpoint-security/src/crowdstrike_tests/fixtures/event_create_indicator_sample.json
  stream/crowdstrike-endpoint-security/src/crowdstrike_tests/fixtures/event_delete_indicator_sample.json
  stream/crowdstrike-endpoint-security/src/crowdstrike_tests/fixtures/event_update_indicator_sample.json
  stream/crowdstrike-endpoint-security/src/crowdstrike_tests/fixtures/response_file_hash_sample.json
  stream/crowdstrike-endpoint-security/src/crowdstrike_tests/test_crowdstrike.py
Labels: filigran team

#2102 [external-file-stix] Fix stix export (#opencti/issue/5797)
  internal-export-file/export-file-stix/src/export-file-stix.py
Labels: filigran team

#2118 [Malpedia] Fix Malpedia connector import
  external-import/malpedia/src/main.py
Labels: filigran team

#2117 [VirusTotal] Fix updating score
  internal-enrichment/virustotal/src/virustotal/builder.py
Labels: solved, filigran team

#2122 [connectors] list params getter to avoid crashes (#2121)
  internal-export-file/export-file-csv/src/export-file-csv.py
  internal-export-file/export-file-stix/src/export-file-stix.py
  internal-export-file/export-file-txt/src/export-file-txt.py
Labels: bug, filigran team

#2135 [Qradar] Fix error related to type
  stream/qradar/src/config.yml.sample
  stream/qradar/src/qradar.py
Labels: filigran team

#2141 [import-document] Initialize file before import (opencti/6999)
  internal-import-file/import-document/src/reportimporter/core.py
Labels: filigran team

#2140 [Qradar] Fix deprecated API request regarding reference_data
  stream/qradar/src/qradar.py
Labels: filigran team

#2157 [Diode-Import] Fix directory entrypoint.sh
  external-import/diode-import/entrypoint.sh
Labels: filigran team

#2153 [Recorded Future] Fix sources for RF report type
  external-import/recorded-future/src/rflib/rf_to_stix2.py
Labels: filigran team

#2171 Update typo in README.md
  stream/sentinel/README.md
Labels: filigran team

#2175 [Crowdstrike Endpoint Security] Fix import CES import
  stream/crowdstrike-endpoint-security/src/main.py
Labels: filigran team

#2176 [Mandiant] Remove report creation while importing indicators
  external-import/mandiant/src/connector/indicators.py
Labels: filigran team

#2155 [Urlscan] Create an enrichment connector
  internal-enrichment/urlscan-enrichment/.dockerignore
  internal-enrichment/urlscan-enrichment/.gitignore
  internal-enrichment/urlscan-enrichment/Dockerfile
  internal-enrichment/urlscan-enrichment/README.md
  internal-enrichment/urlscan-enrichment/docker-compose.yml
  internal-enrichment/urlscan-enrichment/entrypoint.sh
  internal-enrichment/urlscan-enrichment/src/config.yml.sample
  internal-enrichment/urlscan-enrichment/src/lib/UrlScanEnrichment.py
  internal-enrichment/urlscan-enrichment/src/main.py
  internal-enrichment/urlscan-enrichment/src/requirements.txt
  internal-enrichment/urlscan-enrichment/src/test-requirements.txt
  internal-enrichment/urlscan-enrichment/src/urlscan_enrichment_services/__init__.py
  internal-enrichment/urlscan-enrichment/src/urlscan_enrichment_services/client.py
  internal-enrichment/urlscan-enrichment/src/urlscan_enrichment_services/config_variables.py
  internal-enrichment/urlscan-enrichment/src/urlscan_enrichment_services/constants.py
  internal-enrichment/urlscan-enrichment/src/urlscan_enrichment_services/converter_to_stix2.py
  internal-enrichment/urlscan-enrichment/src/urlscan_enrichment_services/utils.py
Labels: filigran team

#2189 [Qradar] Adding an new environment variable
  stream/qradar/README.md
  stream/qradar/docker-compose.yml
  stream/qradar/src/config.yml.sample
  stream/qradar/src/qradar.py
Labels: filigran team
