Repository OpenCTI-Platform/connectors, pull requests merged in 2024-11, with the labels that each got.

#2885 [Recorded-Future] Fix TypeError, AttributeError and refacto
  external-import/recorded-future/src/rflib/rf_alerts.py
Labels: bug, filigran team

#2904 [connectors] Distribute build time for CI
  .circleci/config.yml
Labels: architecture improvement, filigran team

#2905 [connectors] Add docker_layer_caching for image layers in CI
  .circleci/config.yml
Labels: architecture improvement, filigran team

#2834 [Sentinel-Incidents] Improvment feature
  external-import/sentinel-incidents/Dockerfile
  external-import/sentinel-incidents/README.md
  external-import/sentinel-incidents/docker-compose.yml
  external-import/sentinel-incidents/src/config.yml.sample
  external-import/sentinel-incidents/src/sentinel_incidents_connector/client_api.py
  external-import/sentinel-incidents/src/sentinel_incidents_connector/config_variables.py
  external-import/sentinel-incidents/src/sentinel_incidents_connector/connector.py
  external-import/sentinel-incidents/src/sentinel_incidents_connector/converter_to_stix.py
  external-import/sentinel-incidents/src/sentinel_incidents_connector/utils.py
  stream/sentinel-intel/src/sentinel_intel_connector/api_handler.py
  stream/sentinel-intel/src/sentinel_intel_connector/config_variables.py
Labels: filigran team

#2909 [Sentinel Incidents] Fix dockerfile path
  external-import/sentinel-incidents/Dockerfile
Labels: bug, filigran team

#2914 [Connectors] Remove non-existing arguments for generate_id
  external-import/crits/src/crits.py
  external-import/group-ib/src/data_to_stix2.py
  external-import/ransomwarelive/src/lib/ransom_conn.py
  external-import/recorded-future/src/rflib/rf_to_stix2.py
  internal-enrichment/greynoise/src/main.py
  internal-enrichment/hybrid-analysis-sandbox/src/hybrid-analysis-sandbox.py
  internal-enrichment/orion-malware/src/main.py
  internal-enrichment/recordedfuture-enrichment/src/rflib/rf_to_stix2.py
Labels: bug, filigran team

#2913 [Zerofox] Rename class for botnet, malware, phishing, ransomware models
  external-import/zerofox/src/collectors/mappers/botnetToInfrastructure.py
  external-import/zerofox/src/collectors/mappers/malwareToMalware.py
  external-import/zerofox/src/collectors/mappers/phishingToInfrastructure.py
  external-import/zerofox/src/collectors/mappers/ransomwareToMalware.py
  external-import/zerofox/src/zerofox/domain/botnet.py
  external-import/zerofox/src/zerofox/domain/malware.py
  external-import/zerofox/src/zerofox/domain/phishing.py
  external-import/zerofox/src/zerofox/domain/ransomware.py
Labels: filigran team

#2915 [internal-import] only add object_refs if entity context is a container
  internal-import-file/import-file-misp/src/import-file-misp.py
  internal-import-file/import-file-stix/src/import-file-stix.py
Labels: filigran team

#2948 [Connectors] Add linter check for no generation id stix, no value parameter and unused import in Circle CI
  .circleci/config.yml
  README.md
  shared/pylint_plugins/check_stix_plugin/README.md
Labels: architecture improvement, filigran team

#2944 [Mandiant] Add Mandiant score to IOC instead of confidence
  external-import/mandiant/src/connector/indicators.py
Labels: filigran team

#2937 [Connectors] Revert docker_layer_caching
  .circleci/config.yml
Labels: architecture improvement, filigran team, regression

#2877 [Harfanglab Incidents] Create an external import connector
  external-import/harfanglab-incidents/.dockerignore
  external-import/harfanglab-incidents/Dockerfile
  external-import/harfanglab-incidents/README.md
  external-import/harfanglab-incidents/docker-compose.yml
  external-import/harfanglab-incidents/entrypoint.sh
  external-import/harfanglab-incidents/src/config.yml.sample
  external-import/harfanglab-incidents/src/harfanglab_incidents_connector/__init__.py
  external-import/harfanglab-incidents/src/harfanglab_incidents_connector/client_api.py
  external-import/harfanglab-incidents/src/harfanglab_incidents_connector/config_variables.py
  external-import/harfanglab-incidents/src/harfanglab_incidents_connector/connector.py
  external-import/harfanglab-incidents/src/harfanglab_incidents_connector/constants.py
  external-import/harfanglab-incidents/src/harfanglab_incidents_connector/converter_to_stix.py
  external-import/harfanglab-incidents/src/harfanglab_incidents_connector/models/__init__.py
  external-import/harfanglab-incidents/src/harfanglab_incidents_connector/models/harfanglab.py
  external-import/harfanglab-incidents/src/harfanglab_incidents_connector/models/opencti.py
  external-import/harfanglab-incidents/src/harfanglab_incidents_connector/utils.py
  external-import/harfanglab-incidents/src/main.py
  external-import/harfanglab-incidents/src/requirements.txt
  external-import/harfanglab-incidents/src/test-requirements.txt
Labels: filigran team

#2874 [FLASHPOINT] Deprecate malware and APT mport options
  external-import/flashpoint/README.md
  external-import/flashpoint/docker-compose.yml
  external-import/flashpoint/src/config.yml.sample
  external-import/flashpoint/src/flashpoint.py
Labels: filigran team, do not merge

#2919 [Flashpoint] Fix KeyError "site_source_uri"
  external-import/flashpoint/src/flashpoint.py
Labels: filigran team

#2969 [Crowdstrike] Handle IOCs to be added in the report while importing the report
  external-import/crowdstrike/src/crowdstrike_feeds_connector/core.py
  external-import/crowdstrike/src/crowdstrike_feeds_connector/indicator/builder.py
  external-import/crowdstrike/src/crowdstrike_feeds_connector/indicator/importer.py
  external-import/crowdstrike/src/crowdstrike_feeds_connector/report/builder.py
  external-import/crowdstrike/src/crowdstrike_feeds_connector/report/importer.py
Labels: filigran team

#2876 [Yara] Quick Fix for artefact recovery
  internal-enrichment/yara/src/main.py
Labels: bug, filigran team

#2967 [Tanium] Fix KeyError on non-existing indicator's labels
  stream/tanium/src/import_manager.py
Labels: filigran team

#2968 [RiskIQ - PassiveTotal] Create the enrichment connector
  .circleci/config.yml
  internal-enrichment/riskiq-passive-total/Dockerfile
  internal-enrichment/riskiq-passive-total/README.md
  internal-enrichment/riskiq-passive-total/docker-compose.yml
  internal-enrichment/riskiq-passive-total/entrypoint.sh
  internal-enrichment/riskiq-passive-total/src/config.yml.sample
  internal-enrichment/riskiq-passive-total/src/main.py
  internal-enrichment/riskiq-passive-total/src/requirements.txt
  internal-enrichment/riskiq-passive-total/src/riskiq_passive_total/__init__.py
  internal-enrichment/riskiq-passive-total/src/riskiq_passive_total/client_api.py
  internal-enrichment/riskiq-passive-total/src/riskiq_passive_total/config_variables.py
  internal-enrichment/riskiq-passive-total/src/riskiq_passive_total/connector.py
  internal-enrichment/riskiq-passive-total/src/riskiq_passive_total/converter_to_stix.py
  internal-enrichment/riskiq-passive-total/src/riskiq_passive_total/utils.py
  internal-enrichment/riskiq-passive-total/tests/__init__.py
  internal-enrichment/riskiq-passive-total/tests/common_fixtures.py
  internal-enrichment/riskiq-passive-total/tests/fixtures/data_sample.json
  internal-enrichment/riskiq-passive-total/tests/test-requirements.txt
  internal-enrichment/riskiq-passive-total/tests/test_riskiq_passive_total_connector.py
Labels: filigran team

#2985 [connector] Improve condition in Crowdstrike stream
  stream/crowdstrike-endpoint-security/src/crowdstrike_services/client.py
Labels: filigran team

#2999 [Connectors] Move Qradar in another build
  .circleci/config.yml
Labels: architecture improvement, filigran team

#3009 [Recorded Future] Fix error when getting priority alerts for when getting Alerts
  external-import/recorded-future/src/rflib/pyrf.py
Labels: filigran team

#3019 [Recorded Future] Fix error when getting priority alerts for when getting Alerts
  external-import/recorded-future/src/rflib/pyrf.py
Labels: filigran team

#3014 [Crowdstrike] Improve condition in Crowdstrike stream
  stream/crowdstrike-endpoint-security/src/crowdstrike_services/client.py
Labels: filigran team

#3026 [Recorded Future] Fix import incidents for RF alerts
  external-import/recorded-future/src/rflib/pyrf.py
Labels: filigran team

#3041 [Sentinel-Intel] Fix Error 401 Unauthorized
  stream/sentinel-intel/src/sentinel_intel_connector/api_handler.py
Labels: bug, filigran team, critical

#3018 [Mandiant] fix: infinitely crashes if the state is empty
  external-import/mandiant/src/connector/base.py
  external-import/mandiant/src/connector/errors.py
  external-import/mandiant/src/connector/utils.py
Labels: filigran team

#3043 [Sentinel-Intel] Fix missing init retries_builder
  stream/sentinel-intel/docker-compose.yml
  stream/sentinel-intel/src/config.yml.sample
  stream/sentinel-intel/src/sentinel_intel_connector/api_handler.py
Labels: bug, filigran team
