Repository OpenCTI-Platform/connectors, pull requests merged in 2025-01, with the labels that each got.

#3207 [Intel471] Downgrade Titan-Client lib version to 1.20.0.4
  external-import/intel471/src/requirements.txt
Labels: filigran team, ;|

#3213 [Recorded Future] Handle properly playbook alerts errors to not block the connector
  external-import/recorded-future/README.md
  external-import/recorded-future/__docs__/media/rf-alert-1.png
  external-import/recorded-future/__docs__/media/rf-alert-2.png
  external-import/recorded-future/__docs__/media/rf-alert-3.png
  external-import/recorded-future/__docs__/media/rf-alerting-rules.png
  external-import/recorded-future/__docs__/media/rf-pba-1.png
  external-import/recorded-future/__docs__/media/rf-pba-2.png
  external-import/recorded-future/__docs__/media/rf-pba-3.png
  external-import/recorded-future/__docs__/media/rf-priority-alerts.png
  external-import/recorded-future/__docs__/media/rf-watchlist.png
  external-import/recorded-future/docker-compose.yml
  external-import/recorded-future/src/config.yml.sample
  external-import/recorded-future/src/main.py
  external-import/recorded-future/src/rflib/pyrf.py
  external-import/recorded-future/src/rflib/rf_playbook_alerts.py
  external-import/recorded-future/src/rflib/rf_to_stix2.py
Labels: filigran team

#2730 [stream replication] first version of connectors
  .circleci/config.yml
  external-import/stream-importer/.dockerignore
  external-import/stream-importer/Dockerfile
  external-import/stream-importer/README.md
  external-import/stream-importer/docker-compose.yml
  external-import/stream-importer/entrypoint.sh
  external-import/stream-importer/src/importer/__init__.py
  external-import/stream-importer/src/importer/connector.py
  external-import/stream-importer/src/importer/lib/external_import.py
  external-import/stream-importer/src/importer/metrics.py
  external-import/stream-importer/src/importer/utils.py
  external-import/stream-importer/src/main.py
  external-import/stream-importer/src/requirements.txt
  stream/stream-exporter/.dockerignore
  stream/stream-exporter/Dockerfile
  stream/stream-exporter/README.md
  stream/stream-exporter/docker-compose.yml
  stream/stream-exporter/entrypoint.sh
  stream/stream-exporter/src/config.yml.sample
  stream/stream-exporter/src/connector/__init__.py
  stream/stream-exporter/src/connector/connector.py
  stream/stream-exporter/src/connector/metrics.py
  stream/stream-exporter/src/main.py
  stream/stream-exporter/src/requirements.txt
Labels: community

#3141 [Shadowserver] Fix shadowserver and add additional pytests #3104
  external-import/shadowserver/src/shadowserver/stix_transform.py
  external-import/shadowserver/src/shadowserver/tests/fixtures/report_type_blocklist.json
  external-import/shadowserver/src/shadowserver/tests/fixtures/report_type_device_id.json
  external-import/shadowserver/src/shadowserver/tests/fixtures/report_type_scan_snmp.json
  external-import/shadowserver/src/shadowserver/tests/fixtures/report_type_scan_ssl.json
  external-import/shadowserver/src/shadowserver/tests/fixtures/report_type_scan_ssl_freak.json
  external-import/shadowserver/src/shadowserver/tests/fixtures/report_type_scan_ssl_poodle.json
  external-import/shadowserver/src/shadowserver/tests/test_api.py
  external-import/shadowserver/src/shadowserver/tests/test_stix_transform.py
Labels: community

#3143 Implementation of the TLP:AMBER+STRICT marking on multiple connectors:
  external-import/cisco-sma/README.md
  external-import/cisco-sma/docker-compose.yml
  external-import/cisco-sma/src/cisco_sma.py
  external-import/cisco-sma/src/config.yml.sample
  external-import/crowdstrike/README.md
  external-import/crowdstrike/docker-compose.yml
  external-import/crowdstrike/src/config.yml.sample
  external-import/crowdstrike/src/crowdstrike_feeds_services/utils/constants.py
  external-import/fortinet-ti/README.md
  external-import/fortinet-ti/docker-compose.yml
  external-import/fortinet-ti/src/config.yml.sample
  external-import/fortinet-ti/src/fortinet.py
  external-import/infoblox/README.md
  external-import/infoblox/docker-compose.yml
  external-import/infoblox/src/config.yml.sample
  external-import/infoblox/src/infoblox.py
  external-import/mandiant/README.md
  external-import/mandiant/docker-compose.yml
  external-import/mandiant/src/config.yml.sample
  external-import/mandiant/src/connector/actors.py
  external-import/mandiant/src/connector/base.py
  external-import/mandiant/src/connector/campaigns.py
  external-import/mandiant/src/connector/common.py
  external-import/mandiant/src/connector/constants.py
  external-import/mandiant/src/connector/indicators.py
  external-import/mandiant/src/connector/malwares.py
  external-import/mandiant/src/connector/vulnerabilities.py
  external-import/recorded-future/README.md
  external-import/recorded-future/docker-compose.yml
  external-import/recorded-future/src/rflib/constants.py
Labels: filigran team

#3013 [eset] FIX: Add x_opencti_main_observable_type when missing from atomic indicators
  external-import/eset/src/eset.py
Labels: community

#3036 [taxii2] Bug fixes + Change Report Status
  external-import/taxii2/README.md
  external-import/taxii2/docker-compose.yml
  external-import/taxii2/src/config.yml.sample
  external-import/taxii2/src/connector/client_taxii.py
  external-import/taxii2/src/connector/config_variables.py
  external-import/taxii2/src/connector/connector.py
  external-import/taxii2/src/connector/process_objects.py
Labels: community

#3236 [Orange CyberDefense] MRTI-6741 - OCD Connector
  external-import/orange-cyberdefense/README.md
  external-import/orange-cyberdefense/docker-compose.yml
  external-import/orange-cyberdefense/media/Indicator_1.png
  external-import/orange-cyberdefense/media/Indicator_2.png
  external-import/orange-cyberdefense/media/Indicator_3.png
  external-import/orange-cyberdefense/media/Intrusion_set.png
  external-import/orange-cyberdefense/media/Malware.png
  external-import/orange-cyberdefense/media/Report.png
  external-import/orange-cyberdefense/media/Report_2.png
  external-import/orange-cyberdefense/src/config.yml.sample
  external-import/orange-cyberdefense/src/orange-cyberdefense.py
Labels: partner

#3007 [Zscaler] Stream Connector
  stream/zscaler/Dockerfile
  stream/zscaler/README.md
  stream/zscaler/docker-compose.yml
  stream/zscaler/entrypoint.sh
  stream/zscaler/src/config.yml.sample
  stream/zscaler/src/main.py
  stream/zscaler/src/requirements.txt
  stream/zscaler/src/stream_connector/__init__.py
  stream/zscaler/src/stream_connector/config_variables.py
  stream/zscaler/src/stream_connector/connector.py
  stream/zscaler/src/stream_connector/utils.py
Labels: partner

#2746 Improve ransomware.live connector
  external-import/ransomwarelive/README.md
  external-import/ransomwarelive/src/lib/ransom_conn.py
Labels: community

#2893 [WIZ] Init Connector
  .circleci/config.yml
  external-import/wiz/.dockerignore
  external-import/wiz/Dockerfile
  external-import/wiz/README.md
  external-import/wiz/docker-compose.yml
  external-import/wiz/entrypoint.sh
  external-import/wiz/src/config.yml.sample
  external-import/wiz/src/external_import_connector/__init__.py
  external-import/wiz/src/external_import_connector/client_api.py
  external-import/wiz/src/external_import_connector/config_variables.py
  external-import/wiz/src/external_import_connector/connector.py
  external-import/wiz/src/external_import_connector/converter_to_stix.py
  external-import/wiz/src/external_import_connector/utils.py
  external-import/wiz/src/main.py
  external-import/wiz/src/requirements.txt
  external-import/wiz/src/test-requirements.txt
Labels: community

#3002 [IPSum ] Add connector
  .circleci/config.yml
  external-import/ipsum/.dockerignore
  external-import/ipsum/Dockerfile
  external-import/ipsum/README.md
  external-import/ipsum/docker-compose.yml
  external-import/ipsum/entrypoint.sh
  external-import/ipsum/src/external_import_connector/__init__.py
  external-import/ipsum/src/external_import_connector/client_api.py
  external-import/ipsum/src/external_import_connector/config_variables.py
  external-import/ipsum/src/external_import_connector/connector.py
  external-import/ipsum/src/external_import_connector/converter_to_stix.py
  external-import/ipsum/src/external_import_connector/utils.py
  external-import/ipsum/src/main.py
  external-import/ipsum/src/requirements.txt
Labels: community

#3250 [AbuseSSL] Remove unused variable
  external-import/abuse-ssl/src/abuse-ssl.py
Labels: community

#3261 [WIZ] - Remove unused test_requirements
  external-import/wiz/src/test-requirements.txt
Labels: bug, filigran team, critical

#3272 [All Connectors] Update CircleCI
  .circleci/config.yml
Labels: filigran team

#3249 [Templates] Fix syntax error on entity_in_scope in template
  templates/internal-enrichment/src/internal_enrichment_connector/connector.py
Labels: community

#3033 [Hunt IO] Connector for importing C2 feed into OpenCTI
  external-import/hunt-io/.docker-compose.yml
  external-import/hunt-io/.dockerignore
  external-import/hunt-io/Dockerfile
  external-import/hunt-io/README.md
  external-import/hunt-io/entrypoint.sh
  external-import/hunt-io/src/config.yml.sample
  external-import/hunt-io/src/external_import_connector/__init__.py
  external-import/hunt-io/src/external_import_connector/client_api.py
  external-import/hunt-io/src/external_import_connector/config_variables.py
  external-import/hunt-io/src/external_import_connector/connector.py
  external-import/hunt-io/src/external_import_connector/converter_to_stix.py
  external-import/hunt-io/src/external_import_connector/models.py
  external-import/hunt-io/src/external_import_connector/utils.py
  external-import/hunt-io/src/main.py
  external-import/hunt-io/src/requirements.txt
  external-import/hunt-io/tests/common_fixtures.py
  external-import/hunt-io/tests/fixtures/data_sample.json
  external-import/hunt-io/tests/test-requirements.txt
  external-import/hunt-io/tests/test_template_connector.py
Labels: partner

#3291 [RST Report Hub] Add missing generate id
  external-import/rst-report-hub/src/main.py
Labels: filigran team

#3111 Create IBM X-Force Premier Threat Intelligence Services connector for OpenCTI platform
  external-import/ibm-xti/.dockerignore
  external-import/ibm-xti/.gitignore
  external-import/ibm-xti/Dockerfile
  external-import/ibm-xti/README.md
  external-import/ibm-xti/docker-compose.yml
  external-import/ibm-xti/entrypoint.sh
  external-import/ibm-xti/src/config.yml.sample
  external-import/ibm-xti/src/external_import_connector/__init__.py
  external-import/ibm-xti/src/external_import_connector/client_api.py
  external-import/ibm-xti/src/external_import_connector/config_variables.py
  external-import/ibm-xti/src/external_import_connector/connector.py
  external-import/ibm-xti/src/external_import_connector/formatter.py
  external-import/ibm-xti/src/main.py
  external-import/ibm-xti/src/requirements.txt
  external-import/ibm-xti/tests/common_fixtures.py
  external-import/ibm-xti/tests/fixtures/data_sample.json
  external-import/ibm-xti/tests/test-requirements.txt
  external-import/ibm-xti/tests/test_template_connector.py
  external-import/ibm-xti/utils/set_devenv.sh
Labels: partner

#3307 [CircleCI] Add RST IOC LookUp connector in CI
  .circleci/config.yml
Labels: filigran team

#3310 [CircleCI] Add IBM X-Force in CI
  .circleci/config.yml
Labels: filigran team

#3321 [RST IOC Lookup] Change dependency range for RST IOC Lookup requirements
  internal-enrichment/rst-ioc-lookup/src/requirements.txt
Labels: filigran team

#3327 [AbuseIPDB] Add more accurate logs when issue occurring outside the main process
  internal-enrichment/abuseipdb/src/abuseipdb.py
Labels: filigran team

#3312 [Proofpoint TAP] implement report ingestion use case
  external-import/proofpoint-tap/proofpoint_tap/domain/models/__init__.py
  external-import/proofpoint-tap/proofpoint_tap/domain/models/octi/__init__.py
  external-import/proofpoint-tap/proofpoint_tap/domain/models/octi/common.py
  external-import/proofpoint-tap/proofpoint_tap/domain/models/octi/domain.py
  external-import/proofpoint-tap/proofpoint_tap/domain/models/octi/observables.py
  external-import/proofpoint-tap/proofpoint_tap/domain/models/octi/relationships.py
  external-import/proofpoint-tap/proofpoint_tap/domain/use_cases/ingest_report.py
  external-import/proofpoint-tap/proofpoint_tap/ports/campaign.py
  external-import/proofpoint-tap/tests/test-requirements.txt
  external-import/proofpoint-tap/tests/test_domain/test_use_cases/test_ingest_report.py
Labels: filigran team, do not merge

#3339 [Crowdstrike] Correct imports are incorrectly sorted and/or formatted
  external-import/crowdstrike/src/crowdstrike_feeds_connector/indicator/builder.py
Labels: filigran team

#3346 [All connectors] Fix Update format following Black dependency upgrade
  external-import/comlaude/src/main.py
  external-import/eset/src/eti_api.py
  external-import/intelfinder/src/intelfinder/__init__.py
  external-import/obstracts/src/taxii2.py
  external-import/sentinel-incidents/src/sentinel_incidents_connector/connector.py
  external-import/siemrules/src/taxii2.py
  external-import/stixify/src/taxii2.py
  external-import/tenable-vuln-management/src/tenable_vuln_management/converter_to_stix.py
  external-import/tenable-vuln-management/src/tenable_vuln_management/models/opencti.py
  external-import/vulmatch/src/taxii2.py
  external-import/zerofox/src/http_/__init__.py
  external-import/zerofox/src/http_/http_request.py
  stream/chronicle/src/common/datetime_converter.py
Labels: filigran team

#3276 [ProofPoint-ET-Reputation] Create the connector external import #2764
  .circleci/config.yml
  external-import/proofpoint-et-reputation/Dockerfile
  external-import/proofpoint-et-reputation/README.md
  external-import/proofpoint-et-reputation/__docs__/media/Author-Organization.png
  external-import/proofpoint-et-reputation/__docs__/media/Indicator-Domain-Name.png
  external-import/proofpoint-et-reputation/__docs__/media/Indicator-IPv4-Addr.png
  external-import/proofpoint-et-reputation/__docs__/media/Observable-Domain-Name.png
  external-import/proofpoint-et-reputation/__docs__/media/Observable-IPv4-Addr.png
  external-import/proofpoint-et-reputation/__docs__/media/Relationship-Domain-Name.png
  external-import/proofpoint-et-reputation/__docs__/media/Relationship-IPv4-Addr.png
  external-import/proofpoint-et-reputation/docker-compose.yml
  external-import/proofpoint-et-reputation/entrypoint.sh
  external-import/proofpoint-et-reputation/pyproject.toml
  external-import/proofpoint-et-reputation/src/__init__.py
  external-import/proofpoint-et-reputation/src/config.yml.sample
  external-import/proofpoint-et-reputation/src/connector/__init__.py
  external-import/proofpoint-et-reputation/src/connector/connector.py
  external-import/proofpoint-et-reputation/src/connector/models/__init__.py
  external-import/proofpoint-et-reputation/src/connector/models/config_variables_models.py
  external-import/proofpoint-et-reputation/src/connector/models/opencti_converter_models.py
  external-import/proofpoint-et-reputation/src/connector/models/reputation_models.py
  external-import/proofpoint-et-reputation/src/connector/services/__init__.py
  external-import/proofpoint-et-reputation/src/connector/services/client_api.py
  external-import/proofpoint-et-reputation/src/connector/services/config_variables.py
  external-import/proofpoint-et-reputation/src/connector/services/converter_to_stix.py
  external-import/proofpoint-et-reputation/src/connector/services/utils.py
  external-import/proofpoint-et-reputation/src/main.py
  external-import/proofpoint-et-reputation/src/requirements.txt
  external-import/proofpoint-et-reputation/tests/conftest.py
  external-import/proofpoint-et-reputation/tests/fixtures/data_sample_domainrepdata.json
  external-import/proofpoint-et-reputation/tests/fixtures/data_sample_iprepdata.json
  external-import/proofpoint-et-reputation/tests/test-requirements.txt
  external-import/proofpoint-et-reputation/tests/test_proofpoint_et_reputation.py
Labels: feature, filigran team

#3328 [CIRCLECI] Dynamic-CI 💡
  .circleci/config.yml
  .circleci/scripts/generate_ci.py
  .circleci/scripts/requirements.txt
  .circleci/templates/dynamic.yml.j2
  .circleci/vars.yml
  external-import/ironnet/Dockerfile
  external-import/sentinelone-threats/Dockerfile
Labels: filigran team

#3377 [Intel471] Downgrade Titan-Client lib version to 1.20.0.4
  external-import/intel471/src/requirements.txt
Labels: filigran team
