Repository OpenCTI-Platform/connectors, pull requests merged in 2025-07, with the labels that each got.

#4211 [Google TI Feeds] indicators in future
  external-import/google-ti-feeds/README.md
  external-import/google-ti-feeds/connector/src/custom/configs/batch_processor_config.py
  external-import/google-ti-feeds/connector/src/custom/mappers/gti_reports/gti_file_to_stix_file.py
  external-import/google-ti-feeds/connector/src/custom/orchestrators/orchestrator.py
  external-import/google-ti-feeds/pyproject.toml
  external-import/google-ti-feeds/tests/custom/mappers/gti_reports/test_gti_file_to_stix_file.py
Labels: filigran team

#4094 [MicrosoftSentinelIntel] Upload API refactor
  stream/microsoft-sentinel-intel/README.md
  stream/microsoft-sentinel-intel/docker-compose.yml
  stream/microsoft-sentinel-intel/src/config.yml.sample
  stream/microsoft-sentinel-intel/src/microsoft_sentinel_intel_connector/api_handler.py
  stream/microsoft-sentinel-intel/src/microsoft_sentinel_intel_connector/config_variables.py
  stream/microsoft-sentinel-intel/src/microsoft_sentinel_intel_connector/connector.py
  stream/microsoft-sentinel-intel/src/requirements.txt
Labels: community, filigran support

#4254 [Shodan InternetDB] Check TLP value to prevent KeyError message
  internal-enrichment/shodan-internetdb/src/shodan_internetdb/config.py
Labels: bug, filigran team

#4116 [glimps_malware] add glimps malware connector
  internal-enrichment/glimps-malware/Dockerfile
  internal-enrichment/glimps-malware/README.md
  internal-enrichment/glimps-malware/docker-compose.yml
  internal-enrichment/glimps-malware/entrypoint.sh
  internal-enrichment/glimps-malware/src/config.yml.sample
  internal-enrichment/glimps-malware/src/glimps_malware_connector/__init__.py
  internal-enrichment/glimps-malware/src/glimps_malware_connector/config_loader.py
  internal-enrichment/glimps-malware/src/glimps_malware_connector/converter_to_stix.py
  internal-enrichment/glimps-malware/src/glimps_malware_connector/glimps_malware.py
  internal-enrichment/glimps-malware/src/main.py
  internal-enrichment/glimps-malware/src/requirements.txt
Labels: partner, new

#4101 [MicrosoftSentinelIntel] Verify
  stream/microsoft-sentinel-intel/README.md
  stream/microsoft-sentinel-intel/src/base_connector/__init__.py
  stream/microsoft-sentinel-intel/src/base_connector/config.py
  stream/microsoft-sentinel-intel/src/base_connector/enums.py
  stream/microsoft-sentinel-intel/src/base_connector/errors.py
  stream/microsoft-sentinel-intel/src/main.py
  stream/microsoft-sentinel-intel/src/microsoft_sentinel_intel/__init__.py
  stream/microsoft-sentinel-intel/src/microsoft_sentinel_intel/client.py
  stream/microsoft-sentinel-intel/src/microsoft_sentinel_intel/config.py
  stream/microsoft-sentinel-intel/src/microsoft_sentinel_intel/connector.py
  stream/microsoft-sentinel-intel/src/microsoft_sentinel_intel/errors.py
  stream/microsoft-sentinel-intel/src/microsoft_sentinel_intel/utils.py
  stream/microsoft-sentinel-intel/src/microsoft_sentinel_intel_connector/__init__.py
  stream/microsoft-sentinel-intel/src/microsoft_sentinel_intel_connector/api_handler.py
  stream/microsoft-sentinel-intel/src/microsoft_sentinel_intel_connector/config_variables.py
  stream/microsoft-sentinel-intel/src/microsoft_sentinel_intel_connector/connector.py
  stream/microsoft-sentinel-intel/src/requirements.txt
  stream/microsoft-sentinel-intel/tests/__init__.py
  stream/microsoft-sentinel-intel/tests/base_connector/.env.test
  stream/microsoft-sentinel-intel/tests/base_connector/__init__.py
  stream/microsoft-sentinel-intel/tests/base_connector/config.test.yml
  stream/microsoft-sentinel-intel/tests/base_connector/conftest.py
  stream/microsoft-sentinel-intel/tests/base_connector/test_config.py
  stream/microsoft-sentinel-intel/tests/conftest.py
  stream/microsoft-sentinel-intel/tests/microsoft_sentinel_intel/__init__.py
  stream/microsoft-sentinel-intel/tests/microsoft_sentinel_intel/conftest.py
  stream/microsoft-sentinel-intel/tests/microsoft_sentinel_intel/test_config.py
  stream/microsoft-sentinel-intel/tests/microsoft_sentinel_intel/test_connector.py
  stream/microsoft-sentinel-intel/tests/test-requirements.txt
Labels: filigran team, do not merge, filigran verify

#4268 [Sekoia] Load `SEKOIA_LIMIT` env as integer
  external-import/sekoia/README.md
  external-import/sekoia/src/sekoia.py
Labels: bug, community

#4293 [Accenture-ACTI] Fix linter
  external-import/accenture-acti/src/accenture_connector/converter_to_stix.py
Labels: filigran team, tiny

#3968 [ShadowServer] Verification
  external-import/shadowserver/.env.sample
  external-import/shadowserver/Dockerfile
  external-import/shadowserver/README.md
  external-import/shadowserver/config.yml.sample
  external-import/shadowserver/docker-compose.yml
  external-import/shadowserver/requirements.txt
  external-import/shadowserver/src/lib/__init__.py
  external-import/shadowserver/src/lib/external_import.py
  external-import/shadowserver/src/main.py
  external-import/shadowserver/src/shadowserver/__init__.py
  external-import/shadowserver/src/shadowserver/api.py
  external-import/shadowserver/src/shadowserver/config.py
  external-import/shadowserver/src/shadowserver/connector.py
  external-import/shadowserver/src/shadowserver/constants.py
  external-import/shadowserver/src/shadowserver/requirements.txt
  external-import/shadowserver/src/shadowserver/stix_transform.py
  external-import/shadowserver/src/shadowserver/utils.py
  external-import/shadowserver/tests/.env.test
  external-import/shadowserver/tests/__init__.py
  external-import/shadowserver/tests/config.test.yml
  external-import/shadowserver/tests/conftest.py
  external-import/shadowserver/tests/fixtures/report_list.json
  external-import/shadowserver/tests/fixtures/report_type_blocklist.json
  external-import/shadowserver/tests/fixtures/report_type_device_id.json
  external-import/shadowserver/tests/fixtures/report_type_scan_cwmp.json
  external-import/shadowserver/tests/fixtures/report_type_scan_http.json
  external-import/shadowserver/tests/fixtures/report_type_scan_ics.json
  external-import/shadowserver/tests/fixtures/report_type_scan_ntp.json
  external-import/shadowserver/tests/fixtures/report_type_scan_snmp.json
  external-import/shadowserver/tests/fixtures/report_type_scan_ssh.json
  external-import/shadowserver/tests/fixtures/report_type_scan_ssl.json
  external-import/shadowserver/tests/fixtures/report_type_scan_ssl_freak.json
  external-import/shadowserver/tests/fixtures/report_type_scan_ssl_poodle.json
  external-import/shadowserver/tests/fixtures/report_type_scan_vnc.json
  external-import/shadowserver/tests/fixtures/subscriptions.json
  external-import/shadowserver/tests/test-requirements.txt
  external-import/shadowserver/tests/test_api.py
  external-import/shadowserver/tests/test_config.py
  external-import/shadowserver/tests/test_connector.py
  external-import/shadowserver/tests/test_stix_transform.py
  external-import/shadowserver/tests/test_utils.py
  stream/microsoft-defender-intel/README.md
Labels: filigran team, filigran verify

#4279 [EmailIntelMicrosoft] Get folder ID instead of given name
  external-import/email-intel-microsoft/src/email_intel_microsoft/client.py
  external-import/email-intel-microsoft/tests/email_intel_microsoft/test_connector.py
Labels: bug, filigran team, tiny

#4186 [Import External Reference] Async, Thread-Safe, and Scalable External Reference Importer with Robust Error Handling
  internal-enrichment/import-external-reference/Dockerfile
  internal-enrichment/import-external-reference/README.md
  internal-enrichment/import-external-reference/src/config.yml.sample
  internal-enrichment/import-external-reference/src/import-external-reference.py
  internal-enrichment/import-external-reference/src/requirements.txt
Labels: community

#4312 [MalwareBazaarRecentAddition] Add required auth key
  external-import/malwarebazaar-recent-additions/docker-compose.yml
  external-import/malwarebazaar-recent-additions/src/config.yml.sample
  external-import/malwarebazaar-recent-additions/src/malwarebazaar-recent-additions.py
Labels: community

#4326 [connectors] Remove strict check of pip audit
  connectors-sdk/tests/conftest.py
  external-import/tenable-security-center/tests/conftest.py
Labels: filigran team, critical

#3927 [Luminar] Threat Intelligence connector.
  external-import/luminar/Dockerfile
  external-import/luminar/README.md
  external-import/luminar/docker-compose.yml
  external-import/luminar/entrypoint.sh
  external-import/luminar/src/config.yml.sample
  external-import/luminar/src/luminar_connector/__init__.py
  external-import/luminar/src/luminar_connector/config_loader.py
  external-import/luminar/src/luminar_connector/connector.py
  external-import/luminar/src/main.py
  external-import/luminar/src/requirements.txt
Labels: community, new

#4352 [google-ti-feeds] Disable fetching of reports outside of the report collection(#4351)
  external-import/google-ti-feeds/connector/src/custom/orchestrators/malware/orchestrator_malware.py
  external-import/google-ti-feeds/connector/src/custom/orchestrators/threat_actor/orchestrator_threat_actor.py
  external-import/google-ti-feeds/tests/custom/test_orchestrator.py
Labels: bug, filigran team

#4340 [s3] Enhance the connector with more mappings V2
  external-import/s3/src/s3.py
Labels: filigran team
