Repository OpenCTI-Platform/connectors, pull requests merged in 2025-05, with the labels that each got.

#3907 [Import Document AI] Import Document AI attaches file to report
  internal-import-file/import-document-ai/src/reportimporter/core.py
Labels: filigran team

#3685 [ReversingLabs] Spectra Analyze Connector bugfix
  internal-enrichment/reversinglabs-malware-presence/README.md
  internal-enrichment/reversinglabs-spectra-analyze/README.md
  internal-enrichment/reversinglabs-spectra-analyze/src/main.py
  internal-enrichment/reversinglabs-spectra-intel-submission/README.md
Labels: partner

#3923 [microsoft-defender-intel] Fix Dockerfile
  stream/microsoft-defender-intel/Dockerfile
Labels: filigran team

#3895 [Ransomwarelive] Fix missing dates
  external-import/ransomwarelive/requirements.txt
  external-import/ransomwarelive/src/lib/ransom_conn.py
Labels: bug, filigran team

#3910 [Disinfox] Rename env var for get_config_variable()
  external-import/disinfox/docker-compose.yml
  external-import/disinfox/src/config.yml.sample
  external-import/disinfox/src/external_import_connector/config_variables.py
Labels: filigran team

#3926 [dogesec cti butler/obstracts/stixify/vulmatch] fix entrypoints for dogesec-*
  external-import/dogesec-ctibutler/entrypoint.sh
  external-import/dogesec-obstracts/entrypoint.sh
  external-import/dogesec-stixify/entrypoint.sh
  external-import/dogesec-vulmatch/entrypoint.sh
Labels: partner

#3925 [Intel471v2] Decrease page number in Reports
  external-import/intel471_v2/changelog.md
  external-import/intel471_v2/src/__version__
  external-import/intel471_v2/src/intel471/streams/reports.py
Labels: partner, filigran verify

#3921 [Feedly] Modify relationship_type when transforming threat actors to intrusion set
  external-import/feedly/src/feedly/opencti_connector/connector.py
Labels: filigran team, filigran support

#3155 [Ransomware Live] Remove need for external API for whois lookups
  external-import/ransomwarelive/src/lib/ransom_conn.py
  internal-enrichment/hygiene/src/requirements.txt
Labels: community

#3942 [ransomwarelive] Add missing whois library
  external-import/ransomwarelive/requirements.txt
Labels: filigran team

#3965 [MalwareBazaar-recent-additions] : fixes
  external-import/malwarebazaar-recent-additions/src/config.yml.sample
  external-import/malwarebazaar-recent-additions/src/malwarebazaar-recent-additions.py
Labels: filigran team

#3806 [MISP Feed] Fixes the incorrect or duplicate mention of the "misp_feed.ssl_verify" environment variable in the README.md file.
  external-import/misp-feed/README.md
Labels: community

#3909 [splunk] Description extraction (issue/3614)
  stream/splunk/src/splunk.py
Labels: community

#3954 [MISP] Add error handling to avoid the connector to crash
  external-import/misp/src/misp.py
  external-import/misp/src/requirements.txt
Labels: filigran team

#4006 [s3] Create the connector (#3997)
  external-import/s3/.dockerignore
  external-import/s3/Dockerfile
  external-import/s3/README.md
  external-import/s3/docker-compose.yml
  external-import/s3/entrypoint.sh
  external-import/s3/src/config.yml.sample
  external-import/s3/src/requirements.txt
  external-import/s3/src/s3.py
  stream/microsoft-graph-security-intel/docker-compose.yml
Labels: filigran team

#3972 [Flashpoint] Add config variables validation
  external-import/flashpoint/.env.sample
  external-import/flashpoint/README.md
  external-import/flashpoint/docker-compose.yml
  external-import/flashpoint/src/config.yml.sample
  external-import/flashpoint/src/flashpoint_connector/client_api.py
  external-import/flashpoint/src/flashpoint_connector/config_loader.py
  external-import/flashpoint/src/flashpoint_connector/config_variables.py
  external-import/flashpoint/src/flashpoint_connector/connector.py
  external-import/flashpoint/src/flashpoint_connector/converter_to_stix.py
  external-import/flashpoint/src/flashpoint_connector/misp_converter_to_stix.py
  external-import/flashpoint/src/requirements.txt
  external-import/flashpoint/tests/config.test.yml
  external-import/flashpoint/tests/conftest.py
  external-import/flashpoint/tests/test-requirements.txt
  external-import/flashpoint/tests/test_config_loader.py
Labels: filigran team

#4004 [Accenture ACTI]: Create a connector
  external-import/accenture-acti/.dockerignore
  external-import/accenture-acti/Dockerfile
  external-import/accenture-acti/README.md
  external-import/accenture-acti/docker-compose.yml
  external-import/accenture-acti/entrypoint.sh
  external-import/accenture-acti/src/accenture_connector/__init__.py
  external-import/accenture-acti/src/accenture_connector/client_api.py
  external-import/accenture-acti/src/accenture_connector/config_loader.py
  external-import/accenture-acti/src/accenture_connector/connector.py
  external-import/accenture-acti/src/accenture_connector/converter_to_stix.py
  external-import/accenture-acti/src/accenture_connector/utils.py
  external-import/accenture-acti/src/config.yml.sample
  external-import/accenture-acti/src/main.py
  external-import/accenture-acti/src/requirements.txt
Labels: filigran team

#4000 [FlashPoint] Implement parameter guess_relationships
  external-import/flashpoint/.env.sample
  external-import/flashpoint/README.md
  external-import/flashpoint/docker-compose.yml
  external-import/flashpoint/src/config.yml.sample
  external-import/flashpoint/src/flashpoint_connector/config_loader.py
  external-import/flashpoint/src/flashpoint_connector/connector.py
  external-import/flashpoint/src/flashpoint_connector/converter_to_stix.py
  external-import/flashpoint/tests/config.test.yml
  external-import/flashpoint/tests/test_config_loader.py
Labels: feature, filigran team

#3723 [Virustotal] Adds Attributes for Virustotal Notes
  internal-enrichment/virustotal/README.md
  internal-enrichment/virustotal/docker-compose.yml
  internal-enrichment/virustotal/src/config.yml.sample
  internal-enrichment/virustotal/src/virustotal/builder.py
  internal-enrichment/virustotal/src/virustotal/client.py
  internal-enrichment/virustotal/src/virustotal/virustotal.py
Labels: community, filigran verify

#3736 [EmailIntelIMAP] Create the connector
  external-import/email-intel-imap/.dockerignore
  external-import/email-intel-imap/.env.sample
  external-import/email-intel-imap/.gitignore
  external-import/email-intel-imap/.pylintrc
  external-import/email-intel-imap/Dockerfile
  external-import/email-intel-imap/README.md
  external-import/email-intel-imap/config.yml.sample
  external-import/email-intel-imap/dev-requirements.txt
  external-import/email-intel-imap/docker-compose.yml
  external-import/email-intel-imap/docs/gmail.md
  external-import/email-intel-imap/docs/pyioga.png
  external-import/email-intel-imap/entrypoint.sh
  external-import/email-intel-imap/mypy.ini
  external-import/email-intel-imap/src/base_connector/__init__.py
  external-import/email-intel-imap/src/base_connector/client.py
  external-import/email-intel-imap/src/base_connector/config.py
  external-import/email-intel-imap/src/base_connector/connector.py
  external-import/email-intel-imap/src/base_connector/converter.py
  external-import/email-intel-imap/src/base_connector/enums.py
  external-import/email-intel-imap/src/base_connector/errors.py
  external-import/email-intel-imap/src/base_connector/models.py
  external-import/email-intel-imap/src/base_connector/requirements.txt
  external-import/email-intel-imap/src/email_intel_imap/__init__.py
  external-import/email-intel-imap/src/email_intel_imap/client.py
  external-import/email-intel-imap/src/email_intel_imap/config.py
  external-import/email-intel-imap/src/email_intel_imap/connector.py
  external-import/email-intel-imap/src/email_intel_imap/converter.py
  external-import/email-intel-imap/src/main.py
  external-import/email-intel-imap/src/requirements.txt
  external-import/email-intel-imap/tests/__init__.py
  external-import/email-intel-imap/tests/base_connector/.env.test
  external-import/email-intel-imap/tests/base_connector/__init__.py
  external-import/email-intel-imap/tests/base_connector/config.test.yml
  external-import/email-intel-imap/tests/base_connector/conftest.py
  external-import/email-intel-imap/tests/base_connector/test_config.py
  external-import/email-intel-imap/tests/base_connector/test_connector.py
  external-import/email-intel-imap/tests/base_connector/test_converter.py
  external-import/email-intel-imap/tests/conftest.py
  external-import/email-intel-imap/tests/email_intel_imap/__init__.py
  external-import/email-intel-imap/tests/email_intel_imap/conftest.py
  external-import/email-intel-imap/tests/email_intel_imap/test_client.py
  external-import/email-intel-imap/tests/email_intel_imap/test_config.py
  external-import/email-intel-imap/tests/email_intel_imap/test_connector.py
  external-import/email-intel-imap/tests/email_intel_imap/test_converter.py
  external-import/email-intel-imap/tests/email_intel_imap/test_main.py
  external-import/email-intel-imap/tests/test-requirements.txt
Labels: filigran team, new

#4042 [EmailIntelImap & EmailIntelMicrosoft] Fix: Align required Pydantic version for connectors with PyCTI dependencies.
  external-import/email-intel-imap/src/base_connector/requirements.txt
  external-import/email-intel-imap/src/requirements.txt
  external-import/email-intel-microsoft/src/base_connector/requirements.txt
  external-import/email-intel-microsoft/src/requirements.txt
Labels: filigran team

#3865 [greynoise] Update to support Suspicious Classification and Sync with Feed
  internal-enrichment/greynoise/README.md
  internal-enrichment/greynoise/docker-compose.yml
  internal-enrichment/greynoise/src/config.yml.sample
  internal-enrichment/greynoise/src/main.py
Labels: partner, filigran verify

#3912 [splunk] Add basic auth for splunk<7.3
  stream/splunk/README.md
  stream/splunk/docker-compose.yml
  stream/splunk/src/config.yml.sample
  stream/splunk/src/splunk.py
Labels: community

#3988 [MicrosoftSentinelIntel] Add infos to case incident description
  external-import/microsoft-sentinel-incidents/src/microsoft_sentinel_incidents_connector/converter_to_stix.py
Labels: filigran team

#4064 [Cofense-ThreatHQ] Create new Cofense connector
  external-import/cofense-threathq/Dockerfile
  external-import/cofense-threathq/README.md
  external-import/cofense-threathq/docker-compose.yml
  external-import/cofense-threathq/entrypoint.sh
  external-import/cofense-threathq/pyproject.toml
  external-import/cofense-threathq/src/config.yml.sample
  external-import/cofense-threathq/src/connector/__init__.py
  external-import/cofense-threathq/src/connector/connector.py
  external-import/cofense-threathq/src/connector/models/__init__.py
  external-import/cofense-threathq/src/connector/models/common.py
  external-import/cofense-threathq/src/connector/models/config_loader.py
  external-import/cofense-threathq/src/connector/services/__init__.py
  external-import/cofense-threathq/src/connector/services/client_api.py
  external-import/cofense-threathq/src/connector/services/config_loader.py
  external-import/cofense-threathq/src/connector/services/converter_to_stix.py
  external-import/cofense-threathq/src/connector/services/utils.py
  external-import/cofense-threathq/src/env.sample
  external-import/cofense-threathq/src/main.py
  external-import/cofense-threathq/src/requirements.txt
Labels: filigran team

#3993 [Sekoia] Allow configuration of API query limit
  external-import/sekoia/README.md
  external-import/sekoia/docker-compose.yml
  external-import/sekoia/src/config.yml.sample
  external-import/sekoia/src/sekoia.py
Labels: filigran verify
