Repository OpenCTI-Platform/connectors, pull requests merged in 2025-06, with the labels that each got.

#4086 [Cofense-ThreatHQ] Add extra parameter to allow
  external-import/cofense-threathq/src/connector/models/common.py
Labels: bug, filigran team

#4025 [Flashpoint] Import CCM Alerts as Incidents
  external-import/flashpoint/.env.sample
  external-import/flashpoint/README.md
  external-import/flashpoint/docker-compose.yml
  external-import/flashpoint/src/config.yml.sample
  external-import/flashpoint/src/flashpoint_client/__init__.py
  external-import/flashpoint/src/flashpoint_client/client_api.py
  external-import/flashpoint/src/flashpoint_client/models/__init__.py
  external-import/flashpoint/src/flashpoint_client/models/compromised_credential_sighting.py
  external-import/flashpoint/src/flashpoint_connector/client_api.py
  external-import/flashpoint/src/flashpoint_connector/config_loader.py
  external-import/flashpoint/src/flashpoint_connector/connector.py
  external-import/flashpoint/src/flashpoint_connector/converter_to_stix.py
  external-import/flashpoint/src/flashpoint_connector/utils.py
  external-import/flashpoint/src/requirements.txt
  external-import/flashpoint/tests/data_samples/search_compromised_credential_sightings_response.json
  external-import/flashpoint/tests/test_flashpoint_client/test_client_api.py
  external-import/flashpoint/tests/test_flashpoint_client/test_models/test_compromised_credential_sighting.py
  external-import/flashpoint/tests/test_flashpoint_connector/config.test.yml
  external-import/flashpoint/tests/test_flashpoint_connector/test_config_loader.py
  external-import/flashpoint/tests/test_flashpoint_connector/test_converter_to_stix.py
Labels: filigran team

#4092 [Recorded Future] Add observables' missing author
  external-import/recorded-future/src/rflib/rf_playbook_alerts.py
  external-import/recorded-future/src/rflib/rf_to_stix2.py
Labels: filigran team

#4087 [MicrosoftSentinelIncident] Add infos to case incident description
  external-import/microsoft-sentinel-incidents/src/microsoft_sentinel_incidents_connector/converter_to_stix.py
Labels: filigran team

#4106 [Ransomwarelive] Fix missing date for targets relationship
  external-import/ransomwarelive/src/lib/ransom_conn.py
Labels: bug, filigran team

#4108 [Microsoft Sentinel Incidents] fix: Parsing Remediation steps should not raise error.
  external-import/microsoft-sentinel-incidents/src/microsoft_sentinel_incidents_connector/converter_to_stix.py
Labels: filigran team

#4127 [S3] Fix error if fixed_bundle is empty
  external-import/s3/src/s3.py
Labels: bug, filigran team

#4119 [Intel471_v2] Deterministic IDs, bug fixes
  external-import/intel471_v2/changelog.md
  external-import/intel471_v2/src/__version__
  external-import/intel471_v2/src/requirements.txt
Labels: critical, partner

#3948 [malwarebazaar] MalwareBazaar Connector that will create a File Observable; Supports disabling of the upload of the actual malware file.
  external-import/malwarebazaar/.dockerignore
  external-import/malwarebazaar/Dockerfile
  external-import/malwarebazaar/README.md
  external-import/malwarebazaar/docker-compose.yml
  external-import/malwarebazaar/entrypoint.sh
  external-import/malwarebazaar/src/config.yml.sample
  external-import/malwarebazaar/src/main.py
  external-import/malwarebazaar/src/malwarebazaar_connector/__init__.py
  external-import/malwarebazaar/src/malwarebazaar_connector/client_api.py
  external-import/malwarebazaar/src/malwarebazaar_connector/config_loader.py
  external-import/malwarebazaar/src/malwarebazaar_connector/connector.py
  external-import/malwarebazaar/src/malwarebazaar_connector/converter_to_stix.py
  external-import/malwarebazaar/src/requirements.txt
Labels: do not merge, partner, new

#4141 [Crowdstrike] Fix error in report
  external-import/crowdstrike/src/crowdstrike_feeds_connector/indicator/builder.py
  external-import/crowdstrike/src/crowdstrike_feeds_connector/indicator/importer.py
  external-import/crowdstrike/src/crowdstrike_feeds_connector/report/importer.py
Labels: filigran team

#4133 [URLScan-Enrichment] Fix error when no snapshot
  internal-enrichment/urlscan-enrichment/src/main.py
  internal-enrichment/urlscan-enrichment/src/urlscan_enrichment_services/client.py
  internal-enrichment/urlscan-enrichment/src/urlscan_enrichment_services/utils.py
Labels: filigran team

#4169 [RiskIQ] Add in readme, deprecated connectors
  external-import/riskiq/README.md
  internal-enrichment/riskiq-passive-total/README.md
Labels: filigran team

#4185 [Sekoia] Small fixes + add new config on importing IOC related object
  external-import/sekoia/README.md
  external-import/sekoia/docker-compose.yml
  external-import/sekoia/src/config.yml.sample
  external-import/sekoia/src/sekoia.py
Labels: filigran team

#4188 [ServiceNow] Fix entrypoint
  external-import/servicenow/entrypoint.sh
Labels: bug, filigran team
