Repository OpenCTI-Platform/connectors, pull requests merged in 2025-03, with the labels that each got.

#3527 [microsoft-sentinel-incidents] Error during imports related to the datetime format on the created field.
  external-import/microsoft-sentinel-incidents/src/microsoft_sentinel_incidents_connector/connector.py
  external-import/microsoft-sentinel-incidents/src/microsoft_sentinel_incidents_connector/utils.py
Labels: filigran team

#3541 [Tenable Vuln Management] fix: Connector config loader only works with config.yaml
  external-import/tenable-vuln-management/src/tenable_vuln_management/config_variables.py
Labels: bug, filigran team, critical

#3545 [Tenable Vuln Management] fix: Unhandled CPE URI formats should be skipped
  external-import/tenable-vuln-management/src/tenable_vuln_management/converter_to_stix.py
  external-import/tenable-vuln-management/tests/test_converter_to_stix.py
Labels: bug, filigran team, critical

#3546 [Tenable Vuln Management] fix: inconsistent pagination section presence in response api should be handled gracefully
  external-import/tenable-vuln-management/src/tenable_vuln_management/client_api.py
Labels: bug, filigran team, critical

#3547 [Tenable Vuln Management] fix: last_scan_target attribute inconsistent presence in API response should be handled gracefully
  external-import/tenable-vuln-management/src/tenable_vuln_management/models/tenable.py
Labels: bug, filigran team, critical

#3557 [microsoft-defender-incidents]: Errors when converting “IPEvidence” containing IPv6 addresses
  external-import/microsoft-defender-incidents/src/microsoft_defender_incidents_connector/connector.py
  external-import/microsoft-defender-incidents/src/microsoft_defender_incidents_connector/converter_to_stix.py
  external-import/microsoft-defender-incidents/src/microsoft_defender_incidents_connector/utils.py
Labels: filigran team

#3517 [IPSum] Connector needs improvements
  external-import/ipsum/README.md
  external-import/ipsum/docker-compose.yml
  external-import/ipsum/src/config.yml.sample
  external-import/ipsum/src/external_import_connector/config_variables.py
  external-import/ipsum/src/external_import_connector/connector.py
  external-import/ipsum/src/external_import_connector/converter_to_stix.py
Labels: filigran team, filigran verify

#3505 [Dragos]: feat implement api client
  external-import/dragos/client_api/README.md
  external-import/dragos/client_api/common.py
  external-import/dragos/client_api/dev/docs/demo_v1_product.png
  external-import/dragos/client_api/dev/docs/demo_v1_related_indicator.png
  external-import/dragos/client_api/dev/fake_server/main.py
  external-import/dragos/client_api/dev/fake_server/v1/__init__.py
  external-import/dragos/client_api/dev/fake_server/v1/data/indicators.json
  external-import/dragos/client_api/dev/fake_server/v1/data/products.json
  external-import/dragos/client_api/dev/fake_server/v1/indicators.py
  external-import/dragos/client_api/dev/fake_server/v1/product.py
  external-import/dragos/client_api/errors.py
  external-import/dragos/client_api/py.typed
  external-import/dragos/client_api/v1/__init__.py
  external-import/dragos/client_api/v1/common.py
  external-import/dragos/client_api/v1/indicator.py
  external-import/dragos/client_api/v1/product.py
  external-import/dragos/client_api/warning.py
  external-import/dragos/dragos/interfaces/config.py
  external-import/dragos/dragos/interfaces/report.py
  external-import/dragos/pyproject.toml
  external-import/dragos/tests/tests_client_api/tests_v1/test_v1_indicator.py
  external-import/dragos/tests/tests_client_api/tests_v1/test_v1_product.py
Labels: feature, filigran team

#3567 [ALL] - feat: add tools to ensure commits are signed and renovate pr-commit-config
  .github/PULL_REQUEST_TEMPLATE.md
  .pre-commit-config.yaml
  renovate.json
Labels: technical improvement

#3607 [RansomwareLive] Fix import victim key attribute
  external-import/ransomwarelive/src/lib/ransom_conn.py
Labels: filigran team

#3584 [GroupIB] Fix logger + update documentation
  external-import/group-ib/README.md
  external-import/group-ib/src/adapter.py
  external-import/group-ib/src/lib/external_import.py
  external-import/group-ib/src/main.py
  external-import/group-ib/src/utils.py
Labels: filigran team, filigran verify

#3626 [Recorded Future] Fix states usages and best practices
  external-import/recorded-future/README.md
  external-import/recorded-future/src/main.py
  external-import/recorded-future/src/rflib/rf_alerts.py
  external-import/recorded-future/src/rflib/rf_client.py
  external-import/recorded-future/src/rflib/rf_playbook_alerts.py
  external-import/recorded-future/src/rflib/rf_to_stix2.py
  external-import/recorded-future/src/rflib/risk_list.py
  external-import/recorded-future/src/rflib/threat_map.py
Labels: filigran team

#3595 [SocRadar]: Removed extra relationship object as created_by_ref can allow the con…
  external-import/socradar/src/lib/radar.py
Labels: community

#3612 [PROOFPOINT TAP] doc: correct config variable names
  external-import/proofpoint-tap/README.md
Labels: bug, filigran team

#3643 [Silobreaker] Improve error handling while fetching list
  external-import/silobreaker/src/silobreaker.py
Labels: filigran team

#3632 [Proofpoint TAP] fix: siem client should request a minimum 30 seconds interval duration
  external-import/proofpoint-tap/proofpoint_tap/adapters/events.py
  external-import/proofpoint-tap/proofpoint_tap/client_api/v2/siem.py
  external-import/proofpoint-tap/tests/test_adapters/test_events.py
  external-import/proofpoint-tap/tests/test_client_api/test_v2/test_siem.py
Labels: bug, filigran team, critical

#3509 [sentinelone-indicator-stream] A Stream Connector allowing Indicators to be pushed to a SentinelOne Account as IOCs
  stream/sentinelone-indicator/Dockerfile
  stream/sentinelone-indicator/README.md
  stream/sentinelone-indicator/doc/account_id.png
  stream/sentinelone-indicator/doc/api_generation.png
  stream/sentinelone-indicator/doc/stream_creation.png
  stream/sentinelone-indicator/doc/url_finding.png
  stream/sentinelone-indicator/doc/user_creation.png
  stream/sentinelone-indicator/docker-compose.yml
  stream/sentinelone-indicator/entrypoint.sh
  stream/sentinelone-indicator/src/config.yml.sample
  stream/sentinelone-indicator/src/main.py
  stream/sentinelone-indicator/src/requirements.txt
  stream/sentinelone-indicator/src/stream_connector/__init__.py
  stream/sentinelone-indicator/src/stream_connector/config_variables.py
  stream/sentinelone-indicator/src/stream_connector/connector.py
  stream/sentinelone-indicator/src/stream_connector/custom_exceptions.py
  stream/sentinelone-indicator/src/stream_connector/s1_client.py
Labels: community

#3510 [sentinelone-incident-import] A connector that allows Incidents from a SentinelOne Account to be imported into an OpenCTI Instance
  external-import/sentinelone-incidents/Dockerfile
  external-import/sentinelone-incidents/README.md
  external-import/sentinelone-incidents/doc/account_id.png
  external-import/sentinelone-incidents/doc/api_generation.png
  external-import/sentinelone-incidents/doc/tag_note.png
  external-import/sentinelone-incidents/doc/url_finding.png
  external-import/sentinelone-incidents/doc/user_creation.png
  external-import/sentinelone-incidents/docker-compose.yml
  external-import/sentinelone-incidents/entrypoint.sh
  external-import/sentinelone-incidents/src/config.yml.sample
  external-import/sentinelone-incidents/src/external_import_connector/__init__.py
  external-import/sentinelone-incidents/src/external_import_connector/config_variables.py
  external-import/sentinelone-incidents/src/external_import_connector/connector.py
  external-import/sentinelone-incidents/src/external_import_connector/converter_to_stix.py
  external-import/sentinelone-incidents/src/external_import_connector/custom_exceptions.py
  external-import/sentinelone-incidents/src/external_import_connector/s1_client.py
  external-import/sentinelone-incidents/src/main.py
  external-import/sentinelone-incidents/src/requirements.txt
Labels: community

#3648 [sentinelone-incident-import] README fix
  external-import/sentinelone-incidents/README.md
Labels: community

#3649 [sentinelone-indicator-stream] README fix
  stream/sentinelone-indicator/README.md
Labels: community

#3638 [Templates] Isolate config & helper from the connector template
  templates/external-import/src/external_import_connector/connector.py
  templates/external-import/src/main.py
  templates/internal-enrichment/src/internal_enrichment_connector/connector.py
  templates/internal-enrichment/src/main.py
  templates/internal-export-file/src/internal_export_file_connector/connector.py
  templates/internal-export-file/src/main.py
  templates/internal-import-file/src/internal_import_file_connector/connector.py
  templates/internal-import-file/src/main.py
  templates/stream/src/main.py
  templates/stream/src/stream_connector/connector.py
Labels: architecture improvement, filigran team, tiny

#3634 [wiz] fix: author, marking, external references, use of update
  external-import/wiz/Dockerfile
  external-import/wiz/README.md
  external-import/wiz/docker-compose.yml
  external-import/wiz/src/config.yml.sample
  external-import/wiz/src/external_import_connector/config_variables.py
  external-import/wiz/src/external_import_connector/connector.py
  external-import/wiz/src/external_import_connector/converter_to_stix.py
  external-import/wiz/src/main.py
  external-import/wiz/tests/__init__.py
  external-import/wiz/tests/conftest.py
  external-import/wiz/tests/test-requirements.txt
  external-import/wiz/tests/test_wiz_connector.py
Labels: filigran team, to verify, improvement

#3667 [wiz]: fix: Unify and fix datetime comparison
  external-import/wiz/src/external_import_connector/connector.py
  external-import/wiz/tests/test_wiz_connector.py
Labels: bug, filigran team, tiny

#3671 fix(shodan-internetdb): Remove use of deprecated pycti api call
  internal-enrichment/shodan-internetdb/src/shodan_internetdb/connector.py
Labels: bug, filigran team, technical improvement

#3660 [Bambenek] fix: stix id should be determinist, correct observable type is Domain-Name, generated stix objects should be sent to the platform
  external-import/bambenek/src/bambenek_connector/config_variables.py
  external-import/bambenek/src/bambenek_connector/connector.py
  external-import/bambenek/src/bambenek_connector/converter_to_stix.py
Labels: filigran team, to verify

#3683 [RansomwareLive] Remove deprecated variable env update existing data
  external-import/ransomwarelive/.env.sample
  external-import/ransomwarelive/README.md
  external-import/ransomwarelive/docker-compose.yml
  external-import/ransomwarelive/src/lib/ransom_conn.py
Labels: bug, filigran team

#3681 [Ransomwarelive] Fix relationships with the wrong sectors
  external-import/ransomwarelive/src/lib/ransom_conn.py
Labels: bug, filigran team

#3684 [RansomwareLive] Fix error relation_sec_TA
  external-import/ransomwarelive/src/lib/ransom_conn.py
Labels: bug, filigran team

#3548 [Zscaler] Modified category blacklist
  stream/zscaler/src/stream_connector/connector.py
Labels: partner

#3686 [Recorded Future] Fix handling of IPv6 addresses from RF alerts
  external-import/recorded-future/src/rflib/rf_alerts.py
  external-import/recorded-future/src/rflib/rf_playbook_alerts.py
  external-import/recorded-future/src/rflib/utils.py
Labels: bug, filigran team

#3674 [microsoft-sentinel-incidents]: File hashes contained in File Evidence are not correctly converted into Observables
  external-import/microsoft-sentinel-incidents/src/microsoft_sentinel_incidents_connector/converter_to_stix.py
Labels: filigran team

#3676 Microsoft Defender for Endpoint connector data validation errors
  external-import/microsoft-defender-incidents/src/microsoft_defender_incidents_connector/connector.py
  external-import/microsoft-defender-incidents/src/microsoft_defender_incidents_connector/converter_to_stix.py
Labels: filigran team

#3562 [MISP] Adds propagate labels from Event to Attribute option #3495
  external-import/misp/README.md
  external-import/misp/docker-compose.yml
  external-import/misp/src/config.yml.sample
  external-import/misp/src/misp.py
Labels: community

#3672 fix(shodan-internetdb) Fix for verify & refactoring
  internal-enrichment/shodan-internetdb/entrypoint.sh
  internal-enrichment/shodan-internetdb/src/main.py
  internal-enrichment/shodan-internetdb/src/shodan_internetdb/__main__.py
  internal-enrichment/shodan-internetdb/src/shodan_internetdb/client.py
  internal-enrichment/shodan-internetdb/src/shodan_internetdb/config.py
  internal-enrichment/shodan-internetdb/src/shodan_internetdb/connector.py
  internal-enrichment/shodan-internetdb/src/shodan_internetdb/converter_to_stix.py
  internal-enrichment/shodan-internetdb/src/shodan_internetdb/exceptions.py
  internal-enrichment/shodan-internetdb/tests/conftest.py
  internal-enrichment/shodan-internetdb/tests/test-requirements.txt
  internal-enrichment/shodan-internetdb/tests/test_shodan_internet_db_connector.py
Labels: filigran team, improvement

#3688 [Dragos] feat: implement geocoding interface
  external-import/dragos/dragos/interfaces/__init__.py
  external-import/dragos/dragos/interfaces/common.py
  external-import/dragos/dragos/interfaces/geocoding.py
  external-import/dragos/dragos/interfaces/report.py
  external-import/dragos/tests/tests_dragos/tests_interfaces/test_geocoding.py
  external-import/dragos/tests/tests_dragos/tests_interfaces/test_report.py
Labels: filigran team
