Repository OpenCTI-Platform/connectors, pull requests merged in 2025-02, with the labels that each got.

#3378 [Proofpoint ET Rep List] Create the connector
  .circleci/templates/dynamic.yml.j2
  external-import/proofpoint-et-reputation/Dockerfile
  external-import/proofpoint-et-reputation/README.md
  external-import/proofpoint-et-reputation/__docs__/media/Author-Organization.png
  external-import/proofpoint-et-reputation/__docs__/media/Indicator-Domain-Name.png
  external-import/proofpoint-et-reputation/__docs__/media/Indicator-IPv4-Addr.png
  external-import/proofpoint-et-reputation/__docs__/media/Observable-Domain-Name.png
  external-import/proofpoint-et-reputation/__docs__/media/Observable-IPv4-Addr.png
  external-import/proofpoint-et-reputation/__docs__/media/Relationship-Domain-Name.png
  external-import/proofpoint-et-reputation/__docs__/media/Relationship-IPv4-Addr.png
  external-import/proofpoint-et-reputation/docker-compose.yml
  external-import/proofpoint-et-reputation/entrypoint.sh
  external-import/proofpoint-et-reputation/pyproject.toml
  external-import/proofpoint-et-reputation/src/__init__.py
  external-import/proofpoint-et-reputation/src/config.yml.sample
  external-import/proofpoint-et-reputation/src/connector/__init__.py
  external-import/proofpoint-et-reputation/src/connector/connector.py
  external-import/proofpoint-et-reputation/src/connector/models/__init__.py
  external-import/proofpoint-et-reputation/src/connector/models/config_variables_models.py
  external-import/proofpoint-et-reputation/src/connector/models/opencti_converter_models.py
  external-import/proofpoint-et-reputation/src/connector/models/reputation_models.py
  external-import/proofpoint-et-reputation/src/connector/services/__init__.py
  external-import/proofpoint-et-reputation/src/connector/services/client_api.py
  external-import/proofpoint-et-reputation/src/connector/services/config_variables.py
  external-import/proofpoint-et-reputation/src/connector/services/converter_to_stix.py
  external-import/proofpoint-et-reputation/src/connector/services/utils.py
  external-import/proofpoint-et-reputation/src/main.py
  external-import/proofpoint-et-reputation/src/requirements.txt
  external-import/proofpoint-et-reputation/tests/conftest.py
  external-import/proofpoint-et-reputation/tests/fixtures/data_sample_domainrepdata.json
  external-import/proofpoint-et-reputation/tests/fixtures/data_sample_iprepdata.json
  external-import/proofpoint-et-reputation/tests/test-requirements.txt
  external-import/proofpoint-et-reputation/tests/test_proofpoint_et_reputation.py
Labels: filigran team

#3072 [socradar] Add SOCRadar external import connector
  external-import/socradar/Dockerfile
  external-import/socradar/README.md
  external-import/socradar/entrypoint.sh
  external-import/socradar/requirements.txt
  external-import/socradar/src/config.yml.sample
  external-import/socradar/src/lib/radar.py
  external-import/socradar/src/main.py
Labels: partner

#3353 [Sentinel Incidents] 401 Unauthorized error + missing Directory's path
  external-import/sentinel-incidents/src/sentinel_incidents_connector/client_api.py
  external-import/sentinel-incidents/src/sentinel_incidents_connector/connector.py
  external-import/sentinel-incidents/src/sentinel_incidents_connector/converter_to_stix.py
Labels: filigran team

#3204 [Group-IB] Update Group-IB connector
  external-import/group-ib/.dockerignore
  external-import/group-ib/.env.sample
  external-import/group-ib/.gitignore
  external-import/group-ib/Dockerfile
  external-import/group-ib/README.md
  external-import/group-ib/docker-compose.yml
  external-import/group-ib/docs/configs/endpoints_config.yaml
  external-import/group-ib/requirements.txt
  external-import/group-ib/src/config.py
  external-import/group-ib/src/config.yml.sample
  external-import/group-ib/src/data_to_stix2.py
  external-import/group-ib/src/lib/cyberintegrations-0.6.6-py3-none-any.whl
  external-import/group-ib/src/lib/external_import.py
  external-import/group-ib/src/main.py
  external-import/group-ib/src/utils.py
Labels: partner

#3347 [Spycloud] Create external import connector
  external-import/spycloud/.dockerignore
  external-import/spycloud/Dockerfile
  external-import/spycloud/README.md
  external-import/spycloud/config.yml.sample
  external-import/spycloud/docker-compose.yml.sample
  external-import/spycloud/entrypoint.sh
  external-import/spycloud/main.py
  external-import/spycloud/pyproject.toml
  external-import/spycloud/spycloud_connector/__init__.py
  external-import/spycloud/spycloud_connector/connector.py
  external-import/spycloud/spycloud_connector/models/__init__.py
  external-import/spycloud/spycloud_connector/models/opencti/__init__.py
  external-import/spycloud/spycloud_connector/models/opencti/common.py
  external-import/spycloud/spycloud_connector/models/opencti/domain.py
  external-import/spycloud/spycloud_connector/models/opencti/observables.py
  external-import/spycloud/spycloud_connector/models/opencti/relationships.py
  external-import/spycloud/spycloud_connector/models/spycloud.py
  external-import/spycloud/spycloud_connector/services/__init__.py
  external-import/spycloud/spycloud_connector/services/config_loader.py
  external-import/spycloud/spycloud_connector/services/converter_to_stix.py
  external-import/spycloud/spycloud_connector/services/spycloud_client.py
  external-import/spycloud/spycloud_connector/utils/__init__.py
  external-import/spycloud/spycloud_connector/utils/decorators.py
  external-import/spycloud/spycloud_connector/utils/helpers.py
  external-import/spycloud/tests/data_samples/breach_catalog_api_response.json
  external-import/spycloud/tests/data_samples/breach_records_api_response.json
  external-import/spycloud/tests/test_models/test_opencti_common.py
  external-import/spycloud/tests/test_models/test_opencti_domain.py
  external-import/spycloud/tests/test_models/test_opencti_observables.py
  external-import/spycloud/tests/test_models/test_opencti_relationships.py
  external-import/spycloud/tests/test_models/test_spycloud.py
  external-import/spycloud/tests/test_services/test_converter_to_stix.py
  external-import/spycloud/tests/test_services/test_spycloud_client.py
Labels: filigran team, do not merge, new

#3381 [GroupIB] Remove copy .env in Dockerfile
  external-import/group-ib/Dockerfile
Labels: filigran team

#3324 [Hatching Triage Sandbox] URL analysis support + Playbook compatibility
  internal-enrichment/hatching-triage-sandbox/docker-compose.yml
  internal-enrichment/hatching-triage-sandbox/src/config.yml.sample
  internal-enrichment/hatching-triage-sandbox/src/hatching-triage-sandbox.py
Labels: filigran team

#3259 [ImportFileYARA]: Create an import file connector dedicated to import YARA files/rules
  .circleci/vars.yml
  internal-import-file/import-file-yara/.dockerignore
  internal-import-file/import-file-yara/.gitignore
  internal-import-file/import-file-yara/Dockerfile
  internal-import-file/import-file-yara/Dockerfile_fips
  internal-import-file/import-file-yara/README.md
  internal-import-file/import-file-yara/docker-compose.yml
  internal-import-file/import-file-yara/entrypoint.sh
  internal-import-file/import-file-yara/src/config.yml.sample
  internal-import-file/import-file-yara/src/import-file-yara.py
  internal-import-file/import-file-yara/src/requirements.txt
Labels: filigran team

#3384 Update sentinel-incidents docker-compose.yml
  external-import/sentinel-incidents/docker-compose.yml
Labels: filigran team

#3356 Fix connector-cape bugs
  external-import/cape/src/cape/telemetry.py
Labels: community

#3395 [Connectors] Renaming safebrowsing to google-safebrowsing + correction on some docker-compose.yml file
  external-import/spycloud/docker-compose.yml.sample
  internal-enrichment/google-safebrowsing/Dockerfile
  internal-enrichment/google-safebrowsing/README.md
  internal-enrichment/google-safebrowsing/docker-compose.yml
  internal-enrichment/google-safebrowsing/entrypoint.sh
  internal-enrichment/google-safebrowsing/requirements.txt
  internal-enrichment/google-safebrowsing/src/lib/SafeBrowsing.py
  internal-enrichment/google-safebrowsing/src/main.py
  internal-import-file/import-file-yara/docker-compose.yml
Labels: filigran team

#3396 [SENTINEL-INTEL] fix: add explicit error when authentication fails
  stream/sentinel-intel/src/sentinel_intel_connector/api_handler.py
Labels: filigran team

#3398 [Virustotal Livehunt Notifications] Fix ModuleNotFound error
  external-import/virustotal-livehunt-notifications/src/livehunt/builder.py
  external-import/virustotal-livehunt-notifications/src/livehunt/livehunt.py
Labels: bug

#3402 [Zvelo] hot fix: connector stops working if processed data is invalid or incorrectly formatted
  external-import/zvelo/src/zvelo_connector/connector.py
  external-import/zvelo/src/zvelo_connector/converter_to_stix.py
Labels: bug, filigran team

#3387 [Proofpoint TAP] Init
  external-import/proofpoint-tap/.env.sample
  external-import/proofpoint-tap/Dockerfile
  external-import/proofpoint-tap/README.md
  external-import/proofpoint-tap/app.py
  external-import/proofpoint-tap/config.yaml.sample
  external-import/proofpoint-tap/docker-compose.yml.sample
  external-import/proofpoint-tap/proofpoint_tap/__init__.py
  external-import/proofpoint-tap/proofpoint_tap/adapters/__init__.py
  external-import/proofpoint-tap/proofpoint_tap/adapters/campaign.py
  external-import/proofpoint-tap/proofpoint_tap/adapters/config.py
  external-import/proofpoint-tap/proofpoint_tap/adapters/events.py
  external-import/proofpoint-tap/proofpoint_tap/client_api/README.md
  external-import/proofpoint-tap/proofpoint_tap/client_api/__init__.py
  external-import/proofpoint-tap/proofpoint_tap/client_api/common.py
  external-import/proofpoint-tap/proofpoint_tap/client_api/tools.py
  external-import/proofpoint-tap/proofpoint_tap/client_api/v2/__init__.py
  external-import/proofpoint-tap/proofpoint_tap/client_api/v2/campaign.py
  external-import/proofpoint-tap/proofpoint_tap/client_api/v2/compiled_campaign.py
  external-import/proofpoint-tap/proofpoint_tap/client_api/v2/forensics.py
  external-import/proofpoint-tap/proofpoint_tap/client_api/v2/siem.py
  external-import/proofpoint-tap/proofpoint_tap/client_api/v2/threat.py
  external-import/proofpoint-tap/proofpoint_tap/domain/__init__.py
  external-import/proofpoint-tap/proofpoint_tap/domain/models/__init__.py
  external-import/proofpoint-tap/proofpoint_tap/domain/models/octi/__init__.py
  external-import/proofpoint-tap/proofpoint_tap/domain/models/octi/common.py
  external-import/proofpoint-tap/proofpoint_tap/domain/models/octi/domain.py
  external-import/proofpoint-tap/proofpoint_tap/domain/models/octi/observables.py
  external-import/proofpoint-tap/proofpoint_tap/domain/models/octi/relationships.py
  external-import/proofpoint-tap/proofpoint_tap/domain/use_cases/__init__.py
  external-import/proofpoint-tap/proofpoint_tap/domain/use_cases/common.py
  external-import/proofpoint-tap/proofpoint_tap/domain/use_cases/ingest_incident.py
  external-import/proofpoint-tap/proofpoint_tap/domain/use_cases/ingest_report.py
  external-import/proofpoint-tap/proofpoint_tap/errors.py
  external-import/proofpoint-tap/proofpoint_tap/ports/__init__.py
  external-import/proofpoint-tap/proofpoint_tap/ports/campaign.py
  external-import/proofpoint-tap/proofpoint_tap/ports/config.py
  external-import/proofpoint-tap/proofpoint_tap/ports/event.py
  external-import/proofpoint-tap/proofpoint_tap/py.typed
  external-import/proofpoint-tap/proofpoint_tap/warnings.py
  external-import/proofpoint-tap/pyproject.toml
  external-import/proofpoint-tap/tests/test-requirements.txt
  external-import/proofpoint-tap/tests/test_client_api/test_common.py
  external-import/proofpoint-tap/tests/test_client_api/test_tools.py
  external-import/proofpoint-tap/tests/test_client_api/test_v2/test_campaign.py
  external-import/proofpoint-tap/tests/test_client_api/test_v2/test_forensics.py
  external-import/proofpoint-tap/tests/test_client_api/test_v2/test_siem.py
  external-import/proofpoint-tap/tests/test_client_api/test_v2/test_threat.py
  external-import/proofpoint-tap/tests/test_domain/test_use_cases/test_ingest_incident.py
  external-import/proofpoint-tap/tests/test_domain/test_use_cases/test_ingest_report.py
Labels: filigran team

#3299 [Sekoia] Retrieve the list of entity sources
  external-import/sekoia/README.md
  external-import/sekoia/docker-compose.yml
  external-import/sekoia/src/config.yml.sample
  external-import/sekoia/src/sekoia.py
Labels: filigran team

#3410 [Zvelo] Fix type error
  external-import/zvelo/src/zvelo_connector/converter_to_stix.py
Labels: filigran team

#3401 [client] Add markings support for workbench
  internal-import-file/import-document/src/reportimporter/core.py
  internal-import-file/import-file-misp/src/import-file-misp.py
  internal-import-file/import-file-stix/src/import-file-stix.py
  internal-import-file/import-file-yara/src/import-file-yara.py
Labels: filigran team

#3422 [Recorded Future] Fix unhashable dict issue by getting author ID
  external-import/recorded-future/src/rflib/rf_playbook_alerts.py
Labels: filigran team

#3428 [Connectors] Fix valid_from date in some connectors + format files + correct relationships direction
  external-import/group-ib/src/data_to_stix2.py
  external-import/malpedia/src/malpedia_services/converter_to_stix.py
  external-import/proofpoint-tap/tests/test_domain/test_use_cases/test_ingest_incident.py
  external-import/recorded-future/src/rflib/rf_alerts.py
  external-import/recorded-future/src/rflib/rf_playbook_alerts.py
  external-import/recorded-future/src/rflib/rf_to_stix2.py
  external-import/recorded-future/src/rflib/risk_list.py
  external-import/threatfox/src/main.py
  internal-enrichment/greynoise/src/main.py
  internal-enrichment/ipqs/src/ipqs/builder.py
  internal-enrichment/malbeacon/src/malbeacon_converter.py
  internal-enrichment/recordedfuture-enrichment/src/rflib/rf_to_stix2.py
  internal-enrichment/reversinglabs-malware-presence/src/main.py
  internal-enrichment/reversinglabs-spectra-analyze/src/main.py
  internal-enrichment/reversinglabs-spectra-intel-submission/src/main.py
  internal-enrichment/urlscan-enrichment/src/urlscan_enrichment_services/converter_to_stix2.py
  internal-enrichment/virustotal/src/virustotal/builder.py
  internal-import-file/import-file-yara/src/import-file-yara.py
  stream/tanium/src/sightings.py
Labels: filigran team

#3438 [wiz]: Add a connector option to convert threat actor in intrusion-set
  external-import/wiz/README.md
  external-import/wiz/docker-compose.yml
  external-import/wiz/src/config.yml.sample
  external-import/wiz/src/external_import_connector/config_variables.py
  external-import/wiz/src/external_import_connector/connector.py
Labels: filigran team

#3450 [Templates] Update documentation + templates code
  README.md
  templates/README.md
  templates/create_connector_dir.sh
  templates/external-import/docker-compose.yml
  templates/external-import/src/config.yml.sample
  templates/external-import/src/external_import_connector/config_loader.py
  templates/external-import/src/external_import_connector/connector.py
  templates/external-import/src/external_import_connector/converter_to_stix.py
  templates/external-import/src/requirements.txt
  templates/internal-enrichment/src/internal_enrichment_connector/config_loader.py
  templates/internal-enrichment/src/internal_enrichment_connector/connector.py
  templates/internal-enrichment/src/requirements.txt
  templates/internal-export-file/src/internal_export_file_connector/config_loader.py
  templates/internal-export-file/src/internal_export_file_connector/connector.py
  templates/internal-import-file/src/internal_import_file_connector/config_loader.py
  templates/internal-import-file/src/internal_import_file_connector/connector.py
  templates/stream/src/requirements.txt
  templates/stream/src/stream_connector/config_loader.py
  templates/stream/src/stream_connector/connector.py
Labels: filigran team

#3425 [sentinel-intel] Fix (MD5/SHA-1 support & Fix with file metadata)
  stream/sentinel-intel/README.md
  stream/sentinel-intel/src/sentinel_intel_connector/api_handler.py
  stream/sentinel-intel/src/sentinel_intel_connector/connector.py
Labels: filigran team

#3445 [Sentinel-Intel] Improve error handling in Sentinel API client
  stream/sentinel-intel/src/sentinel_intel_connector/api_handler.py
  stream/sentinel-intel/src/sentinel_intel_connector/connector.py
Labels: filigran team

#3463 [tenable vuln management] fix: missing documentation for connector duration period
  external-import/tenable-vuln-management/README.md
  external-import/tenable-vuln-management/src/tenable_vuln_management/config_variables.py
Labels: filigran team

#3464 [CI] fix: drive dependencies with fixed version
  .circleci/config.yml
  ci-requirements.txt
Labels: filigran team

#3115 [attribution-tools] Install gfortran, openblas, xsimd
  internal-enrichment/attribution-tools/Dockerfile
Labels: community

#3459 [Comlaude] connector improvements
  external-import/comlaude/README.md
  external-import/comlaude/docker-compose.yml
  external-import/comlaude/src/config.yml.sample
  external-import/comlaude/src/main.py
Labels: partner

#3139 [urlscan-enrichment] Make indicator creation optional
  internal-enrichment/urlscan-enrichment/README.md
  internal-enrichment/urlscan-enrichment/docker-compose.yml
  internal-enrichment/urlscan-enrichment/src/config.yml.sample
  internal-enrichment/urlscan-enrichment/src/main.py
  internal-enrichment/urlscan-enrichment/src/urlscan_enrichment_services/config_variables.py
Labels: community

#3280 [Bambenek] create bambenek connector
  external-import/bambenek/.dockerignore
  external-import/bambenek/Dockerfile
  external-import/bambenek/README.md
  external-import/bambenek/docker-compose.yml
  external-import/bambenek/entrypoint.sh
  external-import/bambenek/src/bambenek_connector/__init__.py
  external-import/bambenek/src/bambenek_connector/client.py
  external-import/bambenek/src/bambenek_connector/config_variables.py
  external-import/bambenek/src/bambenek_connector/connector.py
  external-import/bambenek/src/bambenek_connector/converter_to_stix.py
  external-import/bambenek/src/bambenek_connector/utils.py
  external-import/bambenek/src/config.yml.sample
  external-import/bambenek/src/main.py
  external-import/bambenek/src/requirements.txt
Labels: feature, community

#3047 [ThreatMatch] Added Beautifulsoup parsing and cleaned up code
  external-import/threatmatch/src/requirements.txt
  external-import/threatmatch/src/threatmatch.py
Labels: partner

#3512 [Bambenek] Fix Dockerfile for CI
  external-import/bambenek/Dockerfile
Labels: filigran team

#3456 Improvement - Ipsum
  external-import/ipsum/src/external_import_connector/client_api.py
  external-import/ipsum/src/external_import_connector/connector.py
  external-import/ipsum/src/external_import_connector/converter_to_stix.py
Labels: bug

#3342 [stream-importer] refine metrics
  external-import/stream-importer/README.md
  external-import/stream-importer/docker-compose.yml
  external-import/stream-importer/src/importer/connector.py
  external-import/stream-importer/src/importer/metrics.py
Labels: community

#3492 [vulncheck ] Use append for SCOPE_SOFTWARE in vulncheck (nistnvd2 source)
  external-import/vulncheck/src/vclib/sources/nistnvd2.py
Labels: community

#3311 [MalwareBazaar] Add SHA256 Indicators and visual change
  external-import/malwarebazaar-recent-additions/src/malwarebazaar-recent-additions.py
Labels: community

#3448 [Taxii2] Handling Int in Config
  external-import/taxii2/src/connector/connector.py
  external-import/taxii2/src/connector/process_objects.py
Labels: community, filigran verify
