Repository OpenCTI-Platform/connectors, pull requests merged in 2025-04, with the labels that each got.

#3693 [Recorded Future] URLencode indicator's value used as Record Future API's endpoint's path params
  external-import/recorded-future/src/rflib/rf_client.py
Labels: bug, filigran team

#3637 [IBM XTI] Enhancements to IBM XTI Connector
  external-import/ibm-xti/README.md
  external-import/ibm-xti/docker-compose.yml
  external-import/ibm-xti/src/config.yml.sample
  external-import/ibm-xti/src/external_import_connector/client_api.py
  external-import/ibm-xti/src/external_import_connector/config_variables.py
  external-import/ibm-xti/src/external_import_connector/connector.py
  external-import/ibm-xti/src/external_import_connector/formatter.py
  external-import/ibm-xti/tests/test-requirements.txt
Labels: partner, filigran verify

#3615 [Dragos] Implement OCTI models and use case
  external-import/dragos/dragos/domain/models/__init__.py
  external-import/dragos/dragos/domain/models/octi/__init__.py
  external-import/dragos/dragos/domain/models/octi/common.py
  external-import/dragos/dragos/domain/models/octi/domain.py
  external-import/dragos/dragos/domain/models/octi/enums.py
  external-import/dragos/dragos/domain/models/octi/observables.py
  external-import/dragos/dragos/domain/models/octi/relationships.py
  external-import/dragos/dragos/domain/use_cases/__init__.py
  external-import/dragos/dragos/domain/use_cases/common.py
  external-import/dragos/dragos/domain/use_cases/ingest_report.py
  external-import/dragos/dragos/interfaces/__init__.py
  external-import/dragos/dragos/interfaces/report.py
  external-import/dragos/tests/tests_dragos/test_domain/test_models/test_domain.py
  external-import/dragos/tests/tests_dragos/test_domain/test_models/test_observables.py
  external-import/dragos/tests/tests_dragos/test_domain/test_models/test_relationships.py
  external-import/dragos/tests/tests_dragos/test_domain/test_use_cases/test_ingest_report.py
Labels: filigran team, new

#3669 fix(.pre-commit): Isort needs its own line-length config (https://github.com/astral-sh/ruff/issues/3206)
  .pre-commit-config.yaml
Labels: bug, filigran team, technical improvement

#3729 Thehive fix "updateAt"
  external-import/thehive/src/thehive.py
Labels: community, filigran verify

#3741 fix(wiz): Update README status verified
  external-import/wiz/README.md
Labels: filigran team

#3702 [Tenable security center] feat: inconsistent repository id types in api response could be handled
  external-import/tenable-security-center/tenable_security_center/adapters/tsc_api/v5_13_from_asset.py
  external-import/tenable-security-center/tests/test_adapters/test_tsc_api/test_v5_13_from_asset.py
Labels: filigran team

#3748 [Intel471v2] README: fix INTEL471_PROXY incorrect documentation formating
  external-import/intel471_v2/README.md
Labels: filigran team, filigran support, tiny

#3734 [Sekoia] Fix unused global variable
  external-import/sekoia/src/sekoia.py
Labels: filigran team

#3703 [CATALYST] External Import Connector
  external-import/catalyst/.dockerignore
  external-import/catalyst/Dockerfile
  external-import/catalyst/README.md
  external-import/catalyst/docker-compose.yml
  external-import/catalyst/entrypoint.sh
  external-import/catalyst/requirements.txt
  external-import/catalyst/src/catalyst/__init__.py
  external-import/catalyst/src/catalyst/client_api.py
  external-import/catalyst/src/catalyst/config_loader.py
  external-import/catalyst/src/catalyst/connector.py
  external-import/catalyst/src/config.yml.sample
  external-import/catalyst/src/main.py
  external-import/catalyst/tests/__init__.py
  external-import/catalyst/tests/common_fixtures.py
  external-import/catalyst/tests/conftest.py
  external-import/catalyst/tests/test-requirements.txt
  external-import/catalyst/tests/test_client_api.py
  external-import/catalyst/tests/test_connector.py
Labels: community, new

#3750 [SentinelIntel/MicrosoftGraphSecurityIntel] Handle hostname indicator patterns properly
  stream/microsoft-graph-security-intel/src/microsoft_graph_security_intel_connector/utils.py
  stream/sentinel-intel/src/sentinel_intel_connector/utils.py
Labels: bug, filigran team

#3753 [CI] add auto label filigran team
  .github/workflows/auto-set-labels.yml
Labels: filigran team

#3698 Comlaude Connector Improvement
  external-import/comlaude/src/main.py
Labels: community

#3745 [Dragos] Implement configuration with pydantic-settings
  external-import/dragos/.env.sample
  external-import/dragos/config.yml.sample
  external-import/dragos/dragos/adapters/config/env.py
  external-import/dragos/dragos/adapters/config/yaml.py
  external-import/dragos/dragos/interfaces/__init__.py
  external-import/dragos/dragos/interfaces/config.py
  external-import/dragos/pyproject.toml
  external-import/dragos/tests/test-requirements.txt
  external-import/dragos/tests/tests_dragos/tests_adapters/tests_config/test_env.py
  external-import/dragos/tests/tests_dragos/tests_adapters/tests_config/test_yaml.py
  external-import/dragos/tests/tests_dragos/tests_interfaces/test_config.py
Labels: filigran team

#3819 Revert "Update dependency pyTenable to v1.7.4"
  external-import/tenable-security-center/pyproject.toml
  external-import/tenable-vuln-management/requirements.txt
Labels: bug

#3820 [CVE] Use the correct apiKey field for header
  external-import/cve/src/services/client/api.py
Labels: filigran team

#3744 [EmailIntel] Initialize the connector, config, converter & tests
  external-import/email-intel-imap/.dockerignore
  external-import/email-intel-imap/.env.sample
  external-import/email-intel-imap/.pylintrc
  external-import/email-intel-imap/Dockerfile
  external-import/email-intel-imap/config.yml.sample
  external-import/email-intel-imap/dev-requirements.txt
  external-import/email-intel-imap/docker-compose.yml
  external-import/email-intel-imap/entrypoint.sh
  external-import/email-intel-imap/mypy.ini
  external-import/email-intel-imap/src/base_connector/__init__.py
  external-import/email-intel-imap/src/base_connector/client.py
  external-import/email-intel-imap/src/base_connector/config.py
  external-import/email-intel-imap/src/base_connector/connector.py
  external-import/email-intel-imap/src/base_connector/converter.py
  external-import/email-intel-imap/src/base_connector/enums.py
  external-import/email-intel-imap/src/base_connector/errors.py
  external-import/email-intel-imap/src/base_connector/requirements.txt
  external-import/email-intel-imap/src/email_intel_imap/__init__.py
  external-import/email-intel-imap/src/email_intel_imap/client.py
  external-import/email-intel-imap/src/email_intel_imap/config.py
  external-import/email-intel-imap/src/email_intel_imap/connector.py
  external-import/email-intel-imap/src/email_intel_imap/converter.py
  external-import/email-intel-imap/src/main.py
  external-import/email-intel-imap/src/requirements.txt
  external-import/email-intel-imap/tests/__init__.py
  external-import/email-intel-imap/tests/base_connector/.env.test
  external-import/email-intel-imap/tests/base_connector/__init__.py
  external-import/email-intel-imap/tests/base_connector/config.test.yml
  external-import/email-intel-imap/tests/base_connector/conftest.py
  external-import/email-intel-imap/tests/base_connector/test_config.py
  external-import/email-intel-imap/tests/conftest.py
  external-import/email-intel-imap/tests/email_intel_imap/__init__.py
  external-import/email-intel-imap/tests/email_intel_imap/conftest.py
  external-import/email-intel-imap/tests/email_intel_imap/test_client.py
  external-import/email-intel-imap/tests/email_intel_imap/test_config.py
  external-import/email-intel-imap/tests/email_intel_imap/test_connector.py
  external-import/email-intel-imap/tests/email_intel_imap/test_converter.py
  external-import/email-intel-imap/tests/email_intel_imap/test_main.py
  external-import/email-intel-imap/tests/test-requirements.txt
Labels: filigran team

#3823 [GroupIB] fix: creates both threat actor and intrusion set insteaf of one of them
  external-import/group-ib/README.md
  external-import/group-ib/src/lib/external_import.py
  external-import/group-ib/src/main.py
Labels: filigran team

#3827 [Dragos] Send pdf content alongside report
  external-import/dragos/dragos/domain/models/octi/__init__.py
  external-import/dragos/dragos/domain/models/octi/common.py
  external-import/dragos/dragos/domain/models/octi/domain.py
Labels: filigran team

#3854 [qradar]: No error logs when the connector is not able to contact configured QRadar instance
  stream/qradar/src/qradar.py
Labels: filigran team

#3558 [Disinfox] Create the external-import connector
  external-import/disinfox/.dockerignore
  external-import/disinfox/.gitignore
  external-import/disinfox/Dockerfile
  external-import/disinfox/README.md
  external-import/disinfox/docker-compose.yml
  external-import/disinfox/entrypoint.sh
  external-import/disinfox/example.env
  external-import/disinfox/src/config.yml.sample
  external-import/disinfox/src/external_import_connector/__init__.py
  external-import/disinfox/src/external_import_connector/client_api.py
  external-import/disinfox/src/external_import_connector/config_variables.py
  external-import/disinfox/src/external_import_connector/connector.py
  external-import/disinfox/src/main.py
  external-import/disinfox/src/requirements.txt
  external-import/disinfox/tests/common_fixtures.py
  external-import/disinfox/tests/fixtures/data_sample.json
  external-import/disinfox/tests/test-requirements.txt
  external-import/disinfox/tests/test_template_connector.py
Labels: community, new

#3867 [ShodanInternetDB] Fix playbook
  internal-enrichment/shodan-internetdb/src/shodan_internetdb/connector.py
  internal-enrichment/shodan-internetdb/tests/test_shodan_internet_db_connector.py
Labels: filigran team, tiny, improvement, filigran verify

#3869 [Dragos] Add reports' labels
  external-import/dragos/README.md
  external-import/dragos/dragos/domain/models/octi/domain.py
  external-import/dragos/dragos/domain/use_cases/ingest_report.py
  external-import/dragos/tests/tests_dragos/test_domain/test_models/test_domain.py
Labels: filigran team

#3878 [ShodanInternetDB] Update README status verified
  internal-enrichment/shodan-internetdb/README.md
Labels: filigran team, filigran verify

#3851 [EmailIntel] Handle attachments, add allowed file types config & handle fetch on last run or since relative start date
  external-import/email-intel-imap/.env.sample
  external-import/email-intel-imap/README.md
  external-import/email-intel-imap/config.yml.sample
  external-import/email-intel-imap/src/base_connector/config.py
  external-import/email-intel-imap/src/base_connector/connector.py
  external-import/email-intel-imap/src/base_connector/converter.py
  external-import/email-intel-imap/src/base_connector/models.py
  external-import/email-intel-imap/src/email_intel_imap/config.py
  external-import/email-intel-imap/src/email_intel_imap/connector.py
  external-import/email-intel-imap/src/email_intel_imap/converter.py
  external-import/email-intel-imap/src/main.py
  external-import/email-intel-imap/tests/base_connector/test_config.py
  external-import/email-intel-imap/tests/base_connector/test_connector.py
  external-import/email-intel-imap/tests/base_connector/test_converter.py
  external-import/email-intel-imap/tests/email_intel_imap/conftest.py
  external-import/email-intel-imap/tests/email_intel_imap/test_config.py
  external-import/email-intel-imap/tests/email_intel_imap/test_connector.py
  external-import/email-intel-imap/tests/email_intel_imap/test_converter.py
Labels: filigran team

#3467 [ServiceNow] Create ServiceNow external import connector
  external-import/servicenow/Dockerfile
  external-import/servicenow/README.md
  external-import/servicenow/__docs__/media/ServiceNow-API-Key-New-record.png
  external-import/servicenow/__docs__/media/ServiceNow-API-Key-global.png
  external-import/servicenow/__docs__/media/ServiceNow-Access-Policies.png
  external-import/servicenow/__docs__/media/ServiceNow-Access-Profile-Auth.png
  external-import/servicenow/__docs__/media/ServiceNow-Access-Profile-New-Record.png
  external-import/servicenow/__docs__/media/ServiceNow-Application-Manager-API_Key.png
  external-import/servicenow/__docs__/media/ServiceNow-Application-Manager-SIR.png
  external-import/servicenow/__docs__/media/ServiceNow-Application-Manager.png
  external-import/servicenow/__docs__/media/ServiceNow-Inbound-Auth-Parameters.png
  external-import/servicenow/__docs__/media/ServiceNow-Inbound-Auth-Profile.png
  external-import/servicenow/__docs__/media/ServiceNow-Inbound-Create-Profile.png
  external-import/servicenow/__docs__/media/ServiceNow-Inbound-Profile-Auth-Parameters.png
  external-import/servicenow/__docs__/media/ServiceNow-REST-API-Key.png
  external-import/servicenow/docker-compose.yml
  external-import/servicenow/entrypoint.sh
  external-import/servicenow/pyproject.toml
  external-import/servicenow/src/config.yml.sample
  external-import/servicenow/src/connector/__init__.py
  external-import/servicenow/src/connector/connector.py
  external-import/servicenow/src/connector/models/__init__.py
  external-import/servicenow/src/connector/models/common.py
  external-import/servicenow/src/connector/models/config_loader.py
  external-import/servicenow/src/connector/models/converter.py
  external-import/servicenow/src/connector/models/intelligence.py
  external-import/servicenow/src/connector/services/__init__.py
  external-import/servicenow/src/connector/services/client_api.py
  external-import/servicenow/src/connector/services/config_loader.py
  external-import/servicenow/src/connector/services/converter_to_stix.py
  external-import/servicenow/src/connector/services/utils.py
  external-import/servicenow/src/env.sample
  external-import/servicenow/src/main.py
  external-import/servicenow/src/requirements.txt
  external-import/servicenow/tests/common_fixtures.py
  external-import/servicenow/tests/fixtures/data_sample.json
  external-import/servicenow/tests/test-requirements.txt
  external-import/servicenow/tests/test_client_api.py
  external-import/servicenow/tests/test_template_connector.py
Labels: filigran team

#3898 [Import Document AI] Import Document AI matches existing TTP
  internal-import-file/import-document-ai/src/reportimporter/core.py
  internal-import-file/import-document-ai/src/reportimporter/util.py
Labels: filigran team, filigran verify

#3846 [dogesec] CTI Butler Connector
  external-import/dogesec-ctibutler/.dockerignore
  external-import/dogesec-ctibutler/Dockerfile
  external-import/dogesec-ctibutler/README.md
  external-import/dogesec-ctibutler/config.yml.sample
  external-import/dogesec-ctibutler/docker-compose.yml
  external-import/dogesec-ctibutler/entrypoint.sh
  external-import/dogesec-ctibutler/media/ctibutler-attack.png
  external-import/dogesec-ctibutler/media/ctibutler-icon.png
  external-import/dogesec-ctibutler/media/ctibutler-logo.png
  external-import/dogesec-ctibutler/media/ctibutler-object.png
  external-import/dogesec-ctibutler/requirements.txt
  external-import/dogesec-ctibutler/src/connector.py
Labels: partner, new

#3725 [dogesec-obstracts] Obstracts reimplementation
  external-import/dogesec-obstracts/.dockerignore
  external-import/dogesec-obstracts/Dockerfile
  external-import/dogesec-obstracts/README.md
  external-import/dogesec-obstracts/config.yml.sample
  external-import/dogesec-obstracts/docker-compose.yml
  external-import/dogesec-obstracts/entrypoint.sh
  external-import/dogesec-obstracts/media/obstracts-extraction-graph.png
  external-import/dogesec-obstracts/media/obstracts-icon.png
  external-import/dogesec-obstracts/media/obstracts-logo.png
  external-import/dogesec-obstracts/media/obstracts-subscriptions.png
  external-import/dogesec-obstracts/requirements.txt
  external-import/dogesec-obstracts/src/obstracts.py
  external-import/obstracts/README.md
  external-import/obstracts/docker-compose.yml
  external-import/obstracts/entrypoint.sh
  external-import/obstracts/src/config.yml.sample
  external-import/obstracts/src/requirements.txt
  external-import/obstracts/src/taxii2.py
Labels: partner

#3821 [dogesec-vulmatch] Vulmatch reimplementation
  external-import/dogesec-vulmatch/.dockerignore
  external-import/dogesec-vulmatch/Dockerfile
  external-import/dogesec-vulmatch/README.md
  external-import/dogesec-vulmatch/config.yml.sample
  external-import/dogesec-vulmatch/docker-compose.yml
  external-import/dogesec-vulmatch/entrypoint.sh
  external-import/dogesec-vulmatch/media/vulmatch-cve-list.png
  external-import/dogesec-vulmatch/media/vulmatch-graph.png
  external-import/dogesec-vulmatch/media/vulmatch-icon.png
  external-import/dogesec-vulmatch/media/vulmatch-logo.png
  external-import/dogesec-vulmatch/requirements.txt
  external-import/dogesec-vulmatch/src/connector.py
  external-import/vulmatch/.dockerignore
  external-import/vulmatch/README.md
  external-import/vulmatch/docker-compose.yml
  external-import/vulmatch/entrypoint.sh
  external-import/vulmatch/src/config.yml.sample
  external-import/vulmatch/src/requirements.txt
  external-import/vulmatch/src/taxii2.py
Labels: partner

#3733 [Recorded Future] Implement the possibility to add RiskRules name as labels
  external-import/recorded-future/README.md
  external-import/recorded-future/docker-compose.yml
  external-import/recorded-future/src/config.yml.sample
  external-import/recorded-future/src/main.py
  external-import/recorded-future/src/rflib/rf_to_stix2.py
  external-import/recorded-future/src/rflib/risk_list.py
Labels: filigran team, filigran verify

#3738 [dogesec-stixify] Stixify reimplementation
  external-import/dogesec-stixify/.dockerignore
  external-import/dogesec-stixify/Dockerfile
  external-import/dogesec-stixify/README.md
  external-import/dogesec-stixify/config.yml.sample
  external-import/dogesec-stixify/docker-compose.yml
  external-import/dogesec-stixify/entrypoint.sh
  external-import/dogesec-stixify/media/stixify-dossiers.png
  external-import/dogesec-stixify/media/stixify-graph.png
  external-import/dogesec-stixify/media/stixify-icon.png
  external-import/dogesec-stixify/media/stixify-logo.png
  external-import/dogesec-stixify/media/stixify-reports.png
  external-import/dogesec-stixify/requirements.txt
  external-import/dogesec-stixify/src/connector.py
  external-import/stixify/.dockerignore
  external-import/stixify/README.md
  external-import/stixify/docker-compose.yml
  external-import/stixify/entrypoint.sh
  external-import/stixify/src/config.yml.sample
  external-import/stixify/src/requirements.txt
  external-import/stixify/src/taxii2.py
Labels: partner

#3914 [Dogesec] Fix all connector dogesec for circleci
  external-import/dogesec-ctibutler/Dockerfile
  external-import/dogesec-ctibutler/docker-compose.yml
  external-import/dogesec-ctibutler/entrypoint.sh
  external-import/dogesec-obstracts/Dockerfile
  external-import/dogesec-obstracts/docker-compose.yml
  external-import/dogesec-obstracts/entrypoint.sh
  external-import/dogesec-stixify/Dockerfile
  external-import/dogesec-stixify/docker-compose.yml
  external-import/dogesec-stixify/entrypoint.sh
  external-import/dogesec-vulmatch/Dockerfile
  external-import/dogesec-vulmatch/docker-compose.yml
  external-import/dogesec-vulmatch/entrypoint.sh
Labels: bug, filigran team
