Repository OpenCTI-Platform/connectors, pull requests merged in 2025-08, with the labels that each got.

#4412 [S3] Update README.md
  external-import/s3/README.md
Labels: filigran team

#4277 [RecordedFuture-Enrichment] Enrich OCTI vulnerability (properties only)
  internal-enrichment/recordedfuture-enrichment/README.md
  internal-enrichment/recordedfuture-enrichment/docker-compose.yml
  internal-enrichment/recordedfuture-enrichment/entrypoint.sh
  internal-enrichment/recordedfuture-enrichment/src/config.yml.sample
  internal-enrichment/recordedfuture-enrichment/src/main.py
  internal-enrichment/recordedfuture-enrichment/src/rf_enrichment.py
  internal-enrichment/recordedfuture-enrichment/src/rflib/__init__.py
  internal-enrichment/recordedfuture-enrichment/src/rflib/rf_client.py
  internal-enrichment/recordedfuture-enrichment/src/rflib/rf_connector.py
  internal-enrichment/recordedfuture-enrichment/src/rflib/rf_to_stix2.py
Labels: filigran team

#4442 [ThreatMatch] Cleanup, tests and restructuration
  external-import/threatmatch/src/threatmatch/connector.py
  external-import/threatmatch/tests/threatmatch/conftest.py
  external-import/threatmatch/tests/threatmatch/test_connector.py
Labels: filigran team, filigran verify, connector: threat match

#4439 [S3] Connector crashes trying to parse 'reference'
  external-import/s3/src/s3.py
Labels: filigran team

#4318 [ExportFileYARA]: Create an export file connector dedicated to export YARA rules
  internal-export-file/export-file-yara/Dockerfile
  internal-export-file/export-file-yara/README.md
  internal-export-file/export-file-yara/docker-compose.yml
  internal-export-file/export-file-yara/entrypoint.sh
  internal-export-file/export-file-yara/src/config.yml.sample
  internal-export-file/export-file-yara/src/export_file_yara_connector/__init__.py
  internal-export-file/export-file-yara/src/export_file_yara_connector/config_loader.py
  internal-export-file/export-file-yara/src/export_file_yara_connector/connector.py
  internal-export-file/export-file-yara/src/export_file_yara_connector/utils.py
  internal-export-file/export-file-yara/src/main.py
  internal-export-file/export-file-yara/src/requirements.txt
Labels: filigran team, new

#4452 [ThreatMatch] Implement client
  external-import/threatmatch/src/threatmatch/client.py
  external-import/threatmatch/src/threatmatch/connector.py
Labels: filigran team, filigran verify

#4490 [Shodan] Fix playbook
  internal-enrichment/shodan/src/shodanImport.py
Labels: filigran team, filigran support

#4529 [CircleCI]: Fix test results storage
  run_test.sh
Labels: architecture improvement, filigran team

#4419 [thehive] Fix SSL verify + fix logger issue
  external-import/thehive/src/thehive.py
Labels: filigran team, do not merge

#4547 [Hygiene] Fix Case is taken into account for Indicator
  internal-enrichment/hygiene/docker-compose.yml
  internal-enrichment/hygiene/src/config.yml.sample
  internal-enrichment/hygiene/src/hygiene.py
Labels: filigran team

#4136 [SocPrime] Initial verification
  external-import/socprime/README.md
  external-import/socprime/docker-compose.yml
  external-import/socprime/src/config.yml.sample
  external-import/socprime/src/main.py
  external-import/socprime/src/requirements.txt
  external-import/socprime/src/socprime/config.py
  external-import/socprime/src/socprime/core.py
  external-import/socprime/src/socprime/mitre_attack.py
  external-import/socprime/src/socprime/tdm_api_client.py
  external-import/socprime/tests/__init__.py
  external-import/socprime/tests/conftest.py
  external-import/socprime/tests/socprime/__init__.py
  external-import/socprime/tests/socprime/conftest.py
  external-import/socprime/tests/socprime/test_config.py
  external-import/socprime/tests/socprime/test_main.py
  external-import/socprime/tests/test-requirements.txt
Labels: filigran team, filigran verify

#4010 [ImportDocIA] feat: integrate relation extraction
  internal-import-file/import-document-ai/README.md
  internal-import-file/import-document-ai/dev/Dockerfile
  internal-import-file/import-document-ai/dev/README.md
  internal-import-file/import-document-ai/dev/dev-requirements.txt
  internal-import-file/import-document-ai/dev/docker-compose.yml
  internal-import-file/import-document-ai/dev/fake_rest.py
  internal-import-file/import-document-ai/dev/responses/response_400_invalid.json
  internal-import-file/import-document-ai/dev/responses/response_400_missing.json
  internal-import-file/import-document-ai/dev/responses/response_403_trial.json
  internal-import-file/import-document-ai/dev/responses/response_403_unauthorized.json
  internal-import-file/import-document-ai/dev/responses/response_extract_entities_202.json
  internal-import-file/import-document-ai/dev/responses/response_extract_entities_relations_202.json
  internal-import-file/import-document-ai/src/main.py
  internal-import-file/import-document-ai/src/reportimporter/constants.py
  internal-import-file/import-document-ai/src/reportimporter/core.py
  internal-import-file/import-document-ai/src/reportimporter/relations_allowed.py
  internal-import-file/import-document-ai/src/reportimporter/util.py
  internal-import-file/import-document-ai/src/requirements.txt
Labels: filigran team, importDocAI

#4380 [Sumo Logic Intel] Connector to fed Sumo Logic SIEM with indicators
  stream/sumologic-intel/Dockerfile
  stream/sumologic-intel/README.md
  stream/sumologic-intel/docker-compose.yml
  stream/sumologic-intel/entrypoint.sh
  stream/sumologic-intel/src/config.yml.sample
  stream/sumologic-intel/src/main.py
  stream/sumologic-intel/src/requirements.txt
  stream/sumologic-intel/src/sumologic_intel_connector/__init__.py
  stream/sumologic-intel/src/sumologic_intel_connector/api_client.py
  stream/sumologic-intel/src/sumologic_intel_connector/config_loader.py
  stream/sumologic-intel/src/sumologic_intel_connector/connector.py
  stream/sumologic-intel/src/sumologic_intel_connector/utils.py
Labels: filigran team, Sumo Logic siem
